import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {buildChecked,defaultCheckedSeed} from './checked-build.mjs';
const seed=process.env.PSC2_CHECKED_SEED_BIN??defaultCheckedSeed;
const lean='structure TextPair where\n  left : String\n  right : String\ninductive TextChoice where\n  | empty\n  | payload (value : String)\ndef choose (choice : TextChoice) : String :=\n  match choice with\n  | TextChoice.empty => "empty"\n  | TextChoice.payload value => value\ndef pair : TextPair := TextPair.mk "left" "λ😀"\ndef answer : String := choose (TextChoice.payload pair.right)\ndef echo (s : String) : String := s\ndef plain : String := echo "hello"\n';
const ps='structure TextPair where {\n  left : String;\n  right : String;\n};\ninductive TextChoice where {\n  | empty;\n  | payload (value : String);\n};\ndef choose (choice : TextChoice) : String := match choice with {\n  | TextChoice.empty => "empty";\n  | TextChoice.payload value => value;\n};\ndef pair : TextPair := TextPair.mk("left", "λ😀");\ndef answer : String := choose(TextChoice.payload(pair.right));\ndef echo (s : String) : String := s;\ndef plain : String := echo("hello");\n';
for(const kind of ['lean','ps'])test('real '+kind+' String literal, record projection and sum match are owned-checked and executed',{skip:!existsSync(seed)},async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'psc2-owned-text-'));try{await writeFile(path.join(dir,'package.json'),'{"type":"module"}');const entryPath=path.join(dir,'Main.'+kind),outputPath=path.join(dir,'out.js');await writeFile(entryPath,kind==='lean'?lean:ps);
 const receipt=await buildChecked({entryPath,outputPath,seedPath:seed});assert.equal(receipt.kernel.selector,'pskernel-core');assert.equal(receipt.provider.profile,'owned-uniform-algebraic/11');const output=await import(pathToFileURL(outputPath).href);assert.equal(output.answer,'λ😀');assert.equal(output.plain,'hello');assert.equal(output.echo('e\u0301\0😀'),'e\u0301\0😀');
 const input=await readFile(path.join(dir,'out.admissions.json'),'utf8');assert.match(input,/"k":"str"/u);assert.match(input,/"k":"proj"/u);assert(JSON.parse(input).admissions.some(x=>x.kind==='inductive'&&x.declaration.ts[0].cs.length===2));
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('ill-typed String branch rejects without fallback or output',{skip:!existsSync(seed)},async()=>{const dir=await mkdtemp(path.join(tmpdir(),'psc2-owned-text-reject-'));try{const entryPath=path.join(dir,'Main.lean'),outputPath=path.join(dir,'never/out.js');await writeFile(entryPath,lean.replace('TextChoice.empty => "empty"','TextChoice.empty => 42'));await assert.rejects(buildChecked({entryPath,outputPath,seedPath:seed}));assert.equal(existsSync(path.dirname(outputPath)),false);}finally{await rm(dir,{recursive:true,force:true});}});
test('unsupported String operation does not emit through a reference fallback',{skip:!existsSync(seed)},async()=>{const dir=await mkdtemp(path.join(tmpdir(),'psc2-owned-text-operation-'));try{const entryPath=path.join(dir,'Main.lean'),outputPath=path.join(dir,'never/out.js');await writeFile(entryPath,'def answer : Nat := String.Internal.length "hello"\n');await assert.rejects(buildChecked({entryPath,outputPath,seedPath:seed}));assert.equal(existsSync(path.dirname(outputPath)),false);}finally{await rm(dir,{recursive:true,force:true});}});
