import BackendJsFixture
import Ps.BackendJs.Print

def psBackendJsExpected : String :=
  "// generated by ProofScript direct JsIR v1\n" ++
  "export const answer = 42n;\n" ++
  "export function idNat(x) { return x; }\n" ++
  "export function plusOne(x) { return (x + 1n); }\n" ++
  "export function choose(flag, left, right) { return (flag ? left : right); }\n" ++
  "export function callPlusOne(x) { return plusOne(x); }\n" ++
  "export const greeting = \"hello\";\n" ++
  "export const truth = true;\n" ++
  "export const unitValue = undefined;\n"

def psTestBackendJsFixtureEmission : Bool :=
  match psBackendJsFixtureValidated with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error _ => false
      | Except.ok output =>
          output == psBackendJsExpected

def psBackendJsKeywordModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "class"
        typeParameters := []
        parameters := []
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.literal
            (PsVerifiedIrLiteral.natural 1)
      }
    ]
  }

def psTestBackendJsRejectsKeywordName : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsKeywordModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            (PsJsLowerError.unsupportedName name)) =>
          psStringEq name "class"
      | _ => false

def psBackendJsStructureModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := [
      {
        name := "Box"
        typeParameters := []
        fields := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          }
        ]
      }
    ]
    inductives := []
    declarations := []
  }

def psTestBackendJsRejectsUnsupportedStructure : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsStructureModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.structuresUnsupported) =>
          true
      | _ => false

def psBackendJsUnsupportedIntrinsicModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "mul"
        typeParameters := []
        parameters := [
          {
            name := "left"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          },
          {
            name := "right"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.intrinsic
            PsVerifiedIrIntrinsic.natMul
            []
            [
              PsVerifiedIrExpr.var "left",
              PsVerifiedIrExpr.var "right"
            ]
      }
    ]
  }

def psTestBackendJsRejectsUnsupportedIntrinsic : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsUnsupportedIntrinsicModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedIntrinsic) =>
          true
      | _ => false

def main : IO Unit := do
  if psTestBackendJsFixtureEmission
      && psTestBackendJsRejectsKeywordName
      && psTestBackendJsRejectsUnsupportedStructure
      && psTestBackendJsRejectsUnsupportedIntrinsic then
    IO.println "PSC2_BACKEND_JS_TESTS: PASS"
  else
    throw
      (IO.userError
        "PSC2_BACKEND_JS_TESTS: FAIL")
