import Ps.BackendJs.Module


def jsJ3ExprDecl (name : String) (type : PsVerifiedIrPrimitiveType)
    (body : PsVerifiedIrExpr) : PsVerifiedIrDeclaration :=
  { name := name, typeParameters := [], parameters := [],
    resultType := .primitive type, body := body }


def jsJ3Nat (value : Nat) : PsVerifiedIrExpr :=
  .literal (.natural value)


def jsJ3NatBinaryDecl
    (name : String)
    (resultType : PsVerifiedIrPrimitiveType)
    (operation : PsVerifiedIrIntrinsic)
    (left right : Nat) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name resultType
    (.intrinsic operation [] [jsJ3Nat left, jsJ3Nat right])


def jsJ3NatModule : PsVerifiedIrModule :=
  { psVerifiedIrModuleEmpty with declarations := [
      jsJ3NatBinaryDecl "natAdd" .nat .natAdd 41 1,
      jsJ3NatBinaryDecl "natSub" .nat .natSub 3 5,
      jsJ3NatBinaryDecl "natMul" .nat .natMul 6 7,
      jsJ3NatBinaryDecl "natDiv" .nat .natDiv 9 0,
      jsJ3NatBinaryDecl "natMod" .nat .natMod 9 0,
      jsJ3NatBinaryDecl "natEq" .bool .natEq 7 7,
      jsJ3NatBinaryDecl "natNe" .bool .natNe 7 8,
      jsJ3NatBinaryDecl "natLe" .bool .natLe 7 8,
      jsJ3NatBinaryDecl "natLt" .bool .natLt 7 8
    ] }


def jsJ3ExpectedNatSource : String :=
  "// Generated by ProofScript backend-js (lexical profile).\nexport {};\n" ++
  "const __psc_js_0 = (41n + 1n);\nexport { __psc_js_0 as natAdd };\n" ++
  "const __psc_js_1 = ((__psc_a, __psc_b) => (__psc_a >= __psc_b ? __psc_a - __psc_b : 0n))(3n, 5n);\nexport { __psc_js_1 as natSub };\n" ++
  "const __psc_js_2 = (6n * 7n);\nexport { __psc_js_2 as natMul };\n" ++
  "const __psc_js_3 = ((__psc_a, __psc_b) => (__psc_b === 0n ? 0n : __psc_a / __psc_b))(9n, 0n);\nexport { __psc_js_3 as natDiv };\n" ++
  "const __psc_js_4 = ((__psc_a, __psc_b) => (__psc_b === 0n ? __psc_a : __psc_a % __psc_b))(9n, 0n);\nexport { __psc_js_4 as natMod };\n" ++
  "const __psc_js_5 = (7n === 7n);\nexport { __psc_js_5 as natEq };\n" ++
  "const __psc_js_6 = (7n !== 8n);\nexport { __psc_js_6 as natNe };\n" ++
  "const __psc_js_7 = (7n <= 8n);\nexport { __psc_js_7 as natLe };\n" ++
  "const __psc_js_8 = (7n < 8n);\nexport { __psc_js_8 as natLt };\n"


def psBackendJsJ3NatEmissionTest : Bool :=
  match psJsEmitModule jsJ3NatModule with
  | .error _ => false
  | .ok source => source == jsJ3ExpectedNatSource


#guard psBackendJsJ3NatEmissionTest
