import BackendJsFixture
import Ps.BackendJs.Print

def psBackendJsExpected : String :=
  "// generated by ProofScript direct JsIR v1\n" ++
  "export const answer = 42n;\n" ++
  "export function idNat(x) { return x; }\n" ++
  "export function plusOne(x) { return (x + 1n); }\n" ++
  "export function choose(flag, left, right) { return (flag ? left : right); }\n" ++
  "export function callPlusOne(x) { return plusOne(x); }\n" ++
  "export const greeting = \"hello\";\n" ++
  "export const truth = true;\n" ++
  "export const unitValue = (void 0);\n" ++
  "export function natSubDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_a >= __ps_b ? __ps_a - __ps_b : 0n))(left, right); }\n" ++
  "export function natDivDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? 0n : __ps_a / __ps_b))(left, right); }\n" ++
  "export function natModDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? __ps_a : __ps_a % __ps_b))(left, right); }\n" ++
  "export function intNegDemo(value) { return (-(value)); }\n" ++
  "export function boolAndDemo(left, right) { return (left && right); }\n" ++
  "export function stringLengthDemo(value) { return ((__ps_s) => BigInt(Array.from(__ps_s).length))(value); }\n" ++
  "export function stringUtf8ByteSizeDemo(value) { return ((__ps_s) => { let __ps_n = 0n; for (const __ps_c of __ps_s) { const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); __ps_n += __ps_w; } return __ps_n; })(value); }\n" ++
  "export function stringNextDemo(value, position) { return ((__ps_s, __ps_p) => { let __ps_i = 0n; for (const __ps_c of __ps_s) { const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); if (__ps_i === __ps_p) return __ps_p + __ps_w; if (__ps_i > __ps_p) return __ps_p + 1n; __ps_i += __ps_w; } return __ps_p + 1n; })(value, position); }\n" ++
  "export function stringGetDemo(value, position) { return ((__ps_s, __ps_p) => { let __ps_i = 0n; for (const __ps_c of __ps_s) { if (__ps_i === __ps_p) return __ps_c; if (__ps_i > __ps_p) return \"A\"; const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); __ps_i += __ps_w; } return \"A\"; })(value, position); }\n" ++
  "export function stringAtEndDemo(value, position) { return ((__ps_s, __ps_p) => { let __ps_n = 0n; for (const __ps_c of __ps_s) { const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); __ps_n += __ps_w; } return __ps_p >= __ps_n; })(value, position); }\n" ++
  "export function stringExtractDemo(value, start, stop) { return ((__ps_s, __ps_b, __ps_e) => { if (__ps_b >= __ps_e) return \"\"; let __ps_i = 0n; let __ps_started = false; let __ps_out = \"\"; for (const __ps_c of __ps_s) { const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); if (!__ps_started) { if (__ps_i === __ps_b) __ps_started = true; else { __ps_i += __ps_w; continue; } } if (__ps_i === __ps_e) return __ps_out; __ps_out += __ps_c; __ps_i += __ps_w; } return __ps_out; })(value, start, stop); }\n" ++
  "export function arrayEmptyDemo(capacity) { return (() => { void (capacity); return []; })(); }\n" ++
  "export function arraySizeDemo(array) { return BigInt((array).length); }\n" ++
  "export function arrayPushDemo(array, value) { return [...(array), value]; }\n" ++
  "export function arrayGetDemo(array, index) { return ((__ps_a, __ps_i) => __ps_a[Number(__ps_i)])(array, index); }\n" ++
  "export function arrayGetDDemo(array, index, fallback) { return ((__ps_a, __ps_i, __ps_fallback) => (__ps_i < BigInt(__ps_a.length) ? __ps_a[Number(__ps_i)] : __ps_fallback))(array, index, fallback); }\n" ++
  "export function arraySetDemo(array, index, value) { return ((__ps_a, __ps_i, __ps_v) => { const __ps_out = [...__ps_a]; __ps_out[Number(__ps_i)] = __ps_v; return __ps_out; })(array, index, value); }\n" ++
  "export function arraySetIfInBoundsDemo(array, index, value) { return ((__ps_a, __ps_i, __ps_v) => { if (__ps_i >= BigInt(__ps_a.length)) return __ps_a; const __ps_out = [...__ps_a]; __ps_out[Number(__ps_i)] = __ps_v; return __ps_out; })(array, index, value); }\n" ++
  "export function arrayMapDemo(fn, array) { return ((__ps_f, __ps_a) => __ps_a.map((__ps_x) => __ps_f(__ps_x)))(fn, array); }\n" ++
  "export function arrayFoldDemo(fn, init, array, start, stop) { return ((__ps_f, __ps_init, __ps_a, __ps_start, __ps_stop) => { const __ps_size = BigInt(__ps_a.length); const __ps_end = __ps_stop <= __ps_size ? __ps_stop : __ps_size; let __ps_acc = __ps_init; for (let __ps_i = __ps_start; __ps_i < __ps_end; __ps_i += 1n) { __ps_acc = __ps_f(__ps_acc, __ps_a[Number(__ps_i)]); } return __ps_acc; })(fn, init, array, start, stop); }\n" ++
  "export function u8AddWrap(left, right) { return (((left + right)) & 255); }\n" ++
  "export function i8MulWrap(left, right) { return (((Math.imul(left, right)) << 24) >> 24); }\n" ++
  "export function u64Xor(left, right) { return BigInt.asUintN(64, ((left ^ right))); }\n" ++
  "export function u16Lt(left, right) { return (left < right); }\n" ++
  "export function u8FromNat(value) { return Number(BigInt.asUintN(8, value)); }\n" ++
  "export const u8Literal44 = Number(BigInt.asUintN(8, 44n));\n" ++
  "export function float32Mul(left, right) { return Math.fround((left * right)); }\n" ++
  "export function floatDiv(left, right) { return (left / right); }\n" ++
  "export function letNatDemo(x) { return (() => { const y = (x + 1n); return (y * 2n); })(); }\n" ++
  "export function applyLambda(x) { return ((y) => (y + 2n))(x); }\n"

def psTestBackendJsFixtureEmission : Bool :=
  match psBackendJsFixtureValidated with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error _ => false
      | Except.ok output =>
          output == psBackendJsExpected

def psBackendJsKeywordModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "class"
        typeParameters := []
        parameters := []
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.literal
            (PsVerifiedIrLiteral.natural 1)
      }
    ]
  }

def psTestBackendJsRejectsKeywordName : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsKeywordModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            (PsJsLowerError.unsupportedName name)) =>
          psStringEq name "class"
      | _ => false

def psBackendJsStructureModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := [
      {
        name := "Box"
        typeParameters := []
        fields := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          }
        ]
      }
    ]
    inductives := []
    declarations := []
  }

def psTestBackendJsRejectsUnsupportedStructure : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsStructureModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.structuresUnsupported) =>
          true
      | _ => false

def psBackendJsUnsupportedIntrinsicModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "utf8Size"
        typeParameters := []
        parameters := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.string
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.intrinsic
            PsVerifiedIrIntrinsic.stringUtf8ByteSize
            []
            [PsVerifiedIrExpr.var "value"]
      }
    ]
  }

def psTestBackendJsRejectsUnsupportedIntrinsic : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsUnsupportedIntrinsicModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedIntrinsic) =>
          true
      | _ => false

def psBackendJsWordSizedModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "wordAdd"
        typeParameters := []
        parameters := [
          {
            name := "left"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          },
          {
            name := "right"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.usize
        body :=
          PsVerifiedIrExpr.intrinsic
            (PsVerifiedIrIntrinsic.machineIntBinary
              PsVerifiedIrMachineIntegerType.usize
              PsVerifiedIrIntegerBinaryOp.add)
            []
            [
              PsVerifiedIrExpr.var "left",
              PsVerifiedIrExpr.var "right"
            ]
      }
    ]
  }

def psTestBackendJsRejectsWordSizedWithoutProfile : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsWordSizedModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedType) =>
          true
      | _ => false

def psTestBackendJsMachineIntegerPrinters : Bool :=
  psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint8
        300)
      "Number(BigInt.asUintN(8, 300n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int8
        200)
      "Number(BigInt.asIntN(8, 200n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint64
        5)
      "BigInt.asUintN(64, 5n)"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int64
        (-5))
      "BigInt.asIntN(64, -5n)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint8
        PsJsIrIntegerBinaryOp.add
        "left"
        "right")
      "(((left + right)) & 255)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint16
        PsJsIrIntegerBinaryOp.sub
        "left"
        "right")
      "(((left - right)) & 65535)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.int32
        PsJsIrIntegerBinaryOp.mul
        "left"
        "right")
      "((Math.imul(left, right)) | 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitAnd
        "left"
        "right")
      "(((left & right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitOr
        "left"
        "right")
      "(((left | right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint64
        PsJsIrIntegerBinaryOp.bitXor
        "left"
        "right")
      "BigInt.asUintN(64, ((left ^ right)))"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsFloatPrinters : Bool :=
  psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.add
        "left"
        "right")
      "(left + right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.sub
        "left"
        "right")
      "(left - right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float32
        PsJsIrFloatBinaryOp.mul
        "left"
        "right")
      "Math.fround((left * right))"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.div
        "left"
        "right")
      "(left / right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsUInt8OfNatPrinter : Bool :=
  match
      psJsRuntimeUnary
        PsJsIrRuntimeOp.uint8OfNat
        "value" with
  | Except.ok printed =>
      psStringEq
        printed
        "Number(BigInt.asUintN(8, value))"
  | Except.error _ => false

def main : IO Unit := do
  if psTestBackendJsFixtureEmission
      && psTestBackendJsRejectsKeywordName
      && psTestBackendJsRejectsUnsupportedStructure
      && psTestBackendJsRejectsWordSizedWithoutProfile
      && psTestBackendJsMachineIntegerPrinters
      && psTestBackendJsFloatPrinters
      && psTestBackendJsUInt8OfNatPrinter then
    IO.println "PSC2_BACKEND_JS_TESTS: PASS"
  else
    throw
      (IO.userError
        "PSC2_BACKEND_JS_TESTS: FAIL")
