import Ps.BackendJs.Module


def jsMachineFixtureDecl
    (name : String)
    (primitive : PsVerifiedIrPrimitiveType)
    (machine : PsVerifiedIrMachineIntegerType)
    (value : Int) : PsVerifiedIrDeclaration :=
  {
    name := name,
    typeParameters := [],
    parameters := [],
    resultType := .primitive primitive,
    body := .literal (.machineInteger machine value)
  }


def jsFixedWidthMachineModule : PsVerifiedIrModule :=
  { psVerifiedIrModuleEmpty with declarations := [
      jsMachineFixtureDecl "u8Max" .uint8 .uint8 255,
      jsMachineFixtureDecl "u16Max" .uint16 .uint16 65535,
      jsMachineFixtureDecl "u32Max" .uint32 .uint32 4294967295,
      jsMachineFixtureDecl "u64Max" .uint64 .uint64 18446744073709551615,
      jsMachineFixtureDecl "i8Min" .int8 .int8 (-128),
      jsMachineFixtureDecl "i16Min" .int16 .int16 (-32768),
      jsMachineFixtureDecl "i32Min" .int32 .int32 (-2147483648),
      jsMachineFixtureDecl "i64Min" .int64 .int64 (-9223372036854775808)
    ] }


def jsExpectedFixedWidthMachineSource : String :=
  "// Generated by ProofScript backend-js (lexical profile).\nexport {};\n" ++
  "const __psc_js_0 = 255;\nexport { __psc_js_0 as u8Max };\n" ++
  "const __psc_js_1 = 65535;\nexport { __psc_js_1 as u16Max };\n" ++
  "const __psc_js_2 = 4294967295;\nexport { __psc_js_2 as u32Max };\n" ++
  "const __psc_js_3 = 18446744073709551615n;\nexport { __psc_js_3 as u64Max };\n" ++
  "const __psc_js_4 = -128;\nexport { __psc_js_4 as i8Min };\n" ++
  "const __psc_js_5 = -32768;\nexport { __psc_js_5 as i16Min };\n" ++
  "const __psc_js_6 = -2147483648;\nexport { __psc_js_6 as i32Min };\n" ++
  "const __psc_js_7 = -9223372036854775808n;\nexport { __psc_js_7 as i64Min };\n"


def psBackendJsFixedWidthMachineLiteralTest : Bool :=
  match psJsEmitModule jsFixedWidthMachineModule with
  | .error _ => false
  | .ok source => source == jsExpectedFixedWidthMachineSource


#guard psBackendJsFixedWidthMachineLiteralTest


def psBackendJsRejectsTargetSizedMachineLiteral : Bool :=
  let module : PsVerifiedIrModule :=
    { psVerifiedIrModuleEmpty with declarations := [
        jsMachineFixtureDecl "word" .usize .usize 1
      ] }
  match psJsEmitModule module with
  | .error _ => true
  | .ok _ => false


#guard psBackendJsRejectsTargetSizedMachineLiteral
