import Ps.BackendJs.Module


def jsJ3ExprDecl (name : String) (type : PsVerifiedIrPrimitiveType)
    (body : PsVerifiedIrExpr) : PsVerifiedIrDeclaration :=
  { name := name, typeParameters := [], parameters := [],
    resultType := .primitive type, body := body }


def jsJ3Nat (value : Nat) : PsVerifiedIrExpr :=
  .literal (.natural value)


def jsJ3Int (value : Int) : PsVerifiedIrExpr :=
  .literal (.integer value)


def jsJ3Bool (value : Bool) : PsVerifiedIrExpr :=
  .literal (.bool value)


def jsJ3NatBinaryDecl
    (name : String)
    (resultType : PsVerifiedIrPrimitiveType)
    (operation : PsVerifiedIrIntrinsic)
    (left right : Nat) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name resultType
    (.intrinsic operation [] [jsJ3Nat left, jsJ3Nat right])


def jsJ3IntUnaryDecl
    (name : String)
    (resultType : PsVerifiedIrPrimitiveType)
    (operation : PsVerifiedIrIntrinsic)
    (value : Int) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name resultType
    (.intrinsic operation [] [jsJ3Int value])


def jsJ3IntBinaryDecl
    (name : String)
    (resultType : PsVerifiedIrPrimitiveType)
    (operation : PsVerifiedIrIntrinsic)
    (left right : Int) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name resultType
    (.intrinsic operation [] [jsJ3Int left, jsJ3Int right])


def jsJ3BoolUnaryDecl
    (name : String)
    (operation : PsVerifiedIrIntrinsic)
    (value : Bool) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name .bool
    (.intrinsic operation [] [jsJ3Bool value])


def jsJ3BoolBinaryDecl
    (name : String)
    (operation : PsVerifiedIrIntrinsic)
    (left right : Bool) : PsVerifiedIrDeclaration :=
  jsJ3ExprDecl name .bool
    (.intrinsic operation [] [jsJ3Bool left, jsJ3Bool right])


def jsJ3NatModule : PsVerifiedIrModule :=
  { psVerifiedIrModuleEmpty with declarations := [
      jsJ3NatBinaryDecl "natAdd" .nat .natAdd 41 1,
      jsJ3NatBinaryDecl "natSub" .nat .natSub 3 5,
      jsJ3NatBinaryDecl "natMul" .nat .natMul 6 7,
      jsJ3NatBinaryDecl "natDiv" .nat .natDiv 9 0,
      jsJ3NatBinaryDecl "natMod" .nat .natMod 9 0,
      jsJ3NatBinaryDecl "natEq" .bool .natEq 7 7,
      jsJ3NatBinaryDecl "natNe" .bool .natNe 7 8,
      jsJ3NatBinaryDecl "natLe" .bool .natLe 7 8,
      jsJ3NatBinaryDecl "natLt" .bool .natLt 7 8
    ] }


def jsJ3IntBoolModule : PsVerifiedIrModule :=
  { psVerifiedIrModuleEmpty with declarations := [
      jsJ3ExprDecl "intOfNat" .int (.intrinsic .intOfNat [] [jsJ3Nat 41]),
      jsJ3ExprDecl "intNegSucc" .int (.intrinsic .intNegSucc [] [jsJ3Nat 2]),
      jsJ3IntUnaryDecl "intNeg" .int .intNeg 7,
      jsJ3IntBinaryDecl "intAdd" .int .intAdd (-2) 5,
      jsJ3IntBinaryDecl "intSub" .int .intSub 3 5,
      jsJ3IntBinaryDecl "intMul" .int .intMul (-3) 4,
      jsJ3IntBinaryDecl "intEq" .bool .intEq (-7) (-7),
      jsJ3IntBinaryDecl "intLe" .bool .intLe (-8) 7,
      jsJ3IntBinaryDecl "intLt" .bool .intLt (-8) 7,
      jsJ3IntUnaryDecl "intRepr" .string .intRepr (-42),
      jsJ3BoolUnaryDecl "boolNot" .boolNot true,
      jsJ3BoolBinaryDecl "boolAnd" .boolAnd true false,
      jsJ3BoolBinaryDecl "boolOr" .boolOr false true,
      jsJ3BoolBinaryDecl "boolEq" .boolEq true true,
      jsJ3BoolBinaryDecl "boolNe" .boolNe true false
    ] }


def jsJ3ExpectedNatSource : String :=
  "// Generated by ProofScript backend-js (lexical profile).\nexport {};\n" ++
  "const __psc_js_0 = (41n + 1n);\nexport { __psc_js_0 as natAdd };\n" ++
  "const __psc_js_1 = ((__psc_a, __psc_b) => (__psc_a >= __psc_b ? __psc_a - __psc_b : 0n))(3n, 5n);\nexport { __psc_js_1 as natSub };\n" ++
  "const __psc_js_2 = (6n * 7n);\nexport { __psc_js_2 as natMul };\n" ++
  "const __psc_js_3 = ((__psc_a, __psc_b) => (__psc_b === 0n ? 0n : __psc_a / __psc_b))(9n, 0n);\nexport { __psc_js_3 as natDiv };\n" ++
  "const __psc_js_4 = ((__psc_a, __psc_b) => (__psc_b === 0n ? __psc_a : __psc_a % __psc_b))(9n, 0n);\nexport { __psc_js_4 as natMod };\n" ++
  "const __psc_js_5 = (7n === 7n);\nexport { __psc_js_5 as natEq };\n" ++
  "const __psc_js_6 = (7n !== 8n);\nexport { __psc_js_6 as natNe };\n" ++
  "const __psc_js_7 = (7n <= 8n);\nexport { __psc_js_7 as natLe };\n" ++
  "const __psc_js_8 = (7n < 8n);\nexport { __psc_js_8 as natLt };\n"


def jsJ3ExpectedIntBoolSource : String :=
  "// Generated by ProofScript backend-js (lexical profile).\nexport {};\n" ++
  "const __psc_js_0 = 41n;\nexport { __psc_js_0 as intOfNat };\n" ++
  "const __psc_js_1 = (-(2n + 1n));\nexport { __psc_js_1 as intNegSucc };\n" ++
  "const __psc_js_2 = (-(7n));\nexport { __psc_js_2 as intNeg };\n" ++
  "const __psc_js_3 = (-2n + 5n);\nexport { __psc_js_3 as intAdd };\n" ++
  "const __psc_js_4 = (3n - 5n);\nexport { __psc_js_4 as intSub };\n" ++
  "const __psc_js_5 = (-3n * 4n);\nexport { __psc_js_5 as intMul };\n" ++
  "const __psc_js_6 = (-7n === -7n);\nexport { __psc_js_6 as intEq };\n" ++
  "const __psc_js_7 = (-8n <= 7n);\nexport { __psc_js_7 as intLe };\n" ++
  "const __psc_js_8 = (-8n < 7n);\nexport { __psc_js_8 as intLt };\n" ++
  "const __psc_js_9 = (-42n).toString();\nexport { __psc_js_9 as intRepr };\n" ++
  "const __psc_js_10 = (!true);\nexport { __psc_js_10 as boolNot };\n" ++
  "const __psc_js_11 = (true && false);\nexport { __psc_js_11 as boolAnd };\n" ++
  "const __psc_js_12 = (false || true);\nexport { __psc_js_12 as boolOr };\n" ++
  "const __psc_js_13 = (true === true);\nexport { __psc_js_13 as boolEq };\n" ++
  "const __psc_js_14 = (true !== false);\nexport { __psc_js_14 as boolNe };\n"


def psBackendJsJ3NatEmissionTest : Bool :=
  match psJsEmitModule jsJ3NatModule with
  | .error _ => false
  | .ok source => source == jsJ3ExpectedNatSource


def psBackendJsJ3IntBoolEmissionTest : Bool :=
  match psJsEmitModule jsJ3IntBoolModule with
  | .error _ => false
  | .ok source => source == jsJ3ExpectedIntBoolSource


#guard psBackendJsJ3NatEmissionTest
#guard psBackendJsJ3IntBoolEmissionTest
