import BackendJsFixture
import Ps.BackendJs.Print

def psBackendJsExpected : String :=
  "// generated by ProofScript direct JsIR v1\n" ++
  "export const answer = 42n;\n" ++
  "export function idNat(x) { return x; }\n" ++
  "export function plusOne(x) { return (x + 1n); }\n" ++
  "export function choose(flag, left, right) { return (flag ? left : right); }\n" ++
  "export function callPlusOne(x) { return plusOne(x); }\n" ++
  "export const greeting = \"hello\";\n" ++
  "export const truth = true;\n" ++
  "export const unitValue = (void 0);\n" ++
  "export function natSubDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_a >= __ps_b ? __ps_a - __ps_b : 0n))(left, right); }\n" ++
  "export function natDivDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? 0n : __ps_a / __ps_b))(left, right); }\n" ++
  "export function natModDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? __ps_a : __ps_a % __ps_b))(left, right); }\n" ++
  "export function intNegDemo(value) { return (-(value)); }\n" ++
  "export function boolAndDemo(left, right) { return (left && right); }\n" ++
  "export function stringLengthDemo(value) { return ((__ps_s) => BigInt(Array.from(__ps_s).length))(value); }\n" ++
  "export function u8AddWrap(left, right) { return (((left + right)) & 255); }\n" ++
  "export function i8MulWrap(left, right) { return (((Math.imul(left, right)) << 24) >> 24); }\n" ++
  "export function u64Xor(left, right) { return BigInt.asUintN(64, ((left ^ right))); }\n" ++
  "export function u16Lt(left, right) { return (left < right); }\n" ++
  "export function u8FromNat(value) { return Number(BigInt.asUintN(8, value)); }\n" ++
  "export const u8Literal44 = Number(BigInt.asUintN(8, 44n));\n" ++
  "export function float32Mul(left, right) { return Math.fround((left * right)); }\n" ++
  "export function floatDiv(left, right) { return (left / right); }\n" ++
  "export function letNatDemo(x) { return (() => { const y = (x + 1n); return (y * 2n); })(); }\n" ++
  "export function applyLambda(x) { return ((y) => (y + 2n))(x); }\n"

def psTestBackendJsFixtureEmission : Bool :=
  match psBackendJsFixtureValidated with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error _ => false
      | Except.ok output =>
          output == psBackendJsExpected

def psBackendJsKeywordModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "class"
        typeParameters := []
        parameters := []
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.literal
            (PsVerifiedIrLiteral.natural 1)
      }
    ]
  }

def psTestBackendJsRejectsKeywordName : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsKeywordModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            (PsJsLowerError.unsupportedName name)) =>
          psStringEq name "class"
      | _ => false

def psBackendJsStructureModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := [
      {
        name := "Box"
        typeParameters := []
        fields := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          }
        ]
      }
    ]
    inductives := []
    declarations := []
  }

def psTestBackendJsRejectsUnsupportedStructure : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsStructureModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.structuresUnsupported) =>
          true
      | _ => false

def psBackendJsUnsupportedIntrinsicModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "utf8Size"
        typeParameters := []
        parameters := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.string
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.intrinsic
            PsVerifiedIrIntrinsic.stringUtf8ByteSize
            []
            [PsVerifiedIrExpr.var "value"]
      }
    ]
  }

def psTestBackendJsRejectsUnsupportedIntrinsic : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsUnsupportedIntrinsicModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedIntrinsic) =>
          true
      | _ => false

def psBackendJsWordSizedModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "wordAdd"
        typeParameters := []
        parameters := [
          {
            name := "left"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          },
          {
            name := "right"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.usize
        body :=
          PsVerifiedIrExpr.intrinsic
            (PsVerifiedIrIntrinsic.machineIntBinary
              PsVerifiedIrMachineIntegerType.usize
              PsVerifiedIrIntegerBinaryOp.add)
            []
            [
              PsVerifiedIrExpr.var "left",
              PsVerifiedIrExpr.var "right"
            ]
      }
    ]
  }

def psTestBackendJsRejectsWordSizedWithoutProfile : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsWordSizedModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedType) =>
          true
      | _ => false

def psTestBackendJsMachineIntegerPrinters : Bool :=
  psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint8
        300)
      "Number(BigInt.asUintN(8, 300n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int8
        200)
      "Number(BigInt.asIntN(8, 200n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint64
        5)
      "BigInt.asUintN(64, 5n)"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int64
        (-5))
      "BigInt.asIntN(64, -5n)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint8
        PsJsIrIntegerBinaryOp.add
        "left"
        "right")
      "(((left + right)) & 255)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint16
        PsJsIrIntegerBinaryOp.sub
        "left"
        "right")
      "(((left - right)) & 65535)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.int32
        PsJsIrIntegerBinaryOp.mul
        "left"
        "right")
      "((Math.imul(left, right)) | 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitAnd
        "left"
        "right")
      "(((left & right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitOr
        "left"
        "right")
      "(((left | right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint64
        PsJsIrIntegerBinaryOp.bitXor
        "left"
        "right")
      "BigInt.asUintN(64, ((left ^ right)))"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsFloatPrinters : Bool :=
  psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.add
        "left"
        "right")
      "(left + right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.sub
        "left"
        "right")
      "(left - right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float32
        PsJsIrFloatBinaryOp.mul
        "left"
        "right")
      "Math.fround((left * right))"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.div
        "left"
        "right")
      "(left / right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsUInt8OfNatPrinter : Bool :=
  match
      psJsRuntimeUnary
        PsJsIrRuntimeOp.uint8OfNat
        "value" with
  | Except.ok printed =>
      psStringEq
        printed
        "Number(BigInt.asUintN(8, value))"
  | Except.error _ => false

def main : IO Unit := do
  if psTestBackendJsFixtureEmission
      && psTestBackendJsRejectsKeywordName
      && psTestBackendJsRejectsUnsupportedStructure
      && psTestBackendJsRejectsUnsupportedIntrinsic
      && psTestBackendJsRejectsWordSizedWithoutProfile
      && psTestBackendJsMachineIntegerPrinters
      && psTestBackendJsFloatPrinters
      && psTestBackendJsUInt8OfNatPrinter then
    IO.println "PSC2_BACKEND_JS_TESTS: PASS"
  else
    throw
      (IO.userError
        "PSC2_BACKEND_JS_TESTS: FAIL")
