import {spawn,spawnSync,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {createWriteStream,existsSync} from 'node:fs';
import {pipeline} from 'node:stream/promises';
import {createInterface} from 'node:readline';
import {delimiter,join,resolve} from 'node:path';
import {createModuleArtifact,type JsonValue,type ModuleArtifact,type ModuleDependency} from '@proofscript/module';

export interface LeanVersionInfo {readonly line:string;readonly version:string|null;readonly commit:string|null;readonly build:string|null}
export interface LeanToolchain extends LeanVersionInfo {readonly version:string;readonly binDir:string;readonly executable:string}
export interface DiscoverLeanOptions {readonly binDir?:string;readonly expectedVersion?:string|null;readonly env?:NodeJS.ProcessEnv}
export interface SpawnLeanExporterOptions extends DiscoverLeanOptions {readonly script:string;readonly moduleName:string;readonly args?:readonly string[];readonly cwd?:string}
export interface SpawnLeanExporterResult {readonly toolchain:LeanToolchain;readonly child:ChildProcessWithoutNullStreams;readonly scriptPath:string}
export interface CollectOptions {readonly maxBytes?:number}
export interface CollectedLeanExport {readonly text:string;readonly stderr:string;readonly toolchain:LeanToolchain}
export interface FileLeanExport {readonly file:string;readonly stderr:string;readonly toolchain:LeanToolchain}
export interface ExportModuleArtifactOptions extends SpawnLeanExporterOptions {readonly artifactModule:string;readonly dependencies?:readonly ModuleDependency[];readonly metadata?:JsonValue;readonly maxBytes?:number}

function fail(message:string):never { throw new Error(`@proofscript/lean4export: ${message}`); }
export function parseLeanVersion(text:string):LeanVersionInfo {const line=text.split(/\r?\n/,1)[0]?.trim()??'';const m=/Lean \(version ([^,\s)]+).*commit ([0-9a-f]+).*?(Release|Debug|RelWithDebInfo)?\)?/i.exec(line)??/Lean \(version ([^,\s)]+)/i.exec(line);if(!m)return {line,version:null,commit:null,build:null};return {line,version:m[1]??null,commit:m[2]??null,build:m[3]??null};}
export function discoverLean({binDir,expectedVersion='4.34.0',env=process.env}:DiscoverLeanOptions={}):LeanToolchain {const exeName=process.platform==='win32'?'lean.exe':'lean';const candidates=[binDir,env.LEAN434_BIN,...(env.PATH??'').split(delimiter)].filter((p):p is string=>typeof p==='string'&&p.length>0).map(p=>resolve(p));const found=candidates.find(p=>existsSync(join(p,exeName)));if(found===undefined)fail(`Lean executable '${exeName}' not found; set binDir/LEAN434_BIN or PATH`);const executable=join(found,exeName);const r=spawnSync(executable,['--version'],{encoding:'utf8',env});if(r.error)throw r.error;if(r.status!==0)fail(`Lean --version exited ${r.status}: ${String(r.stderr??'').trim()}`);const info=parseLeanVersion(r.stdout??'');if(info.version===null)fail(`could not parse Lean version from: ${info.line}`);if(expectedVersion!==null&&info.version!==expectedVersion)fail(`expected Lean ${expectedVersion}, got ${info.version}`);return {...info,version:info.version,binDir:found,executable};}
function childEnv(toolchain:LeanToolchain,env:NodeJS.ProcessEnv):NodeJS.ProcessEnv{return {...env,PATH:`${toolchain.binDir}${delimiter}${env.PATH??''}`};}
export function spawnLeanExporter({script,moduleName,args=[],cwd=process.cwd(),binDir,expectedVersion='4.34.0',env=process.env}:SpawnLeanExporterOptions):SpawnLeanExporterResult {if(script.length===0)fail('script is required');if(moduleName.length===0)fail('moduleName is required');const toolchain=discoverLean({...(binDir===undefined?{}:{binDir}),expectedVersion,env});const scriptPath=resolve(cwd,script);const child=spawn(toolchain.executable,['--run',scriptPath,moduleName,...args],{cwd:resolve(cwd),env:childEnv(toolchain,env),stdio:['ignore','pipe','pipe']});return {toolchain,child,scriptPath};}
export async function* streamLeanExporterLines(options:SpawnLeanExporterOptions):AsyncGenerator<string,void,void>{const {child}=spawnLeanExporter(options);let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',(d:string)=>stderr+=d);const rl=createInterface({input:child.stdout,crlfDelay:Infinity});for await(const line of rl)yield line;const [code,signal]=await new Promise<[number|null,NodeJS.Signals|null]>(resolveClose=>child.on('close',(c:number|null,s:NodeJS.Signals|null)=>resolveClose([c,s])));if(code!==0||signal!==null)fail(`Lean exporter exited code=${code} signal=${signal??'none'}\n${stderr}`);}
export async function collectLeanExport(options:SpawnLeanExporterOptions,{maxBytes=64*1024*1024}:CollectOptions={}):Promise<CollectedLeanExport>{if(!Number.isSafeInteger(maxBytes)||maxBytes<1024)fail('maxBytes must be an integer >= 1024');const {child,toolchain}=spawnLeanExporter(options);let stdout='',stderr='',bytes=0,overflow=false;child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');child.stdout.on('data',(d:string)=>{bytes+=Buffer.byteLength(d,'utf8');if(bytes>maxBytes){overflow=true;child.kill('SIGKILL');return;}stdout+=d;});child.stderr.on('data',(d:string)=>stderr+=d);const [code,signal]=await new Promise<[number|null,NodeJS.Signals|null]>(resolveClose=>child.on('close',(c:number|null,s:NodeJS.Signals|null)=>resolveClose([c,s])));if(overflow)fail(`export exceeded maxBytes=${maxBytes}`);if(code!==0||signal!==null)fail(`Lean exporter exited code=${code} signal=${signal??'none'}\n${stderr}`);return {text:stdout,stderr,toolchain};}
export async function exportLeanToFile(options:SpawnLeanExporterOptions,output:string):Promise<FileLeanExport>{const outPath=resolve(output);const {child,toolchain}=spawnLeanExporter(options);let stderr='';child.stderr.setEncoding('utf8');child.stderr.on('data',(d:string)=>stderr+=d);const piping=pipeline(child.stdout,createWriteStream(outPath));const [code,signal]=await new Promise<[number|null,NodeJS.Signals|null]>(resolveClose=>child.on('close',(c:number|null,s:NodeJS.Signals|null)=>resolveClose([c,s])));await piping;if(code!==0||signal!==null)fail(`Lean exporter exited code=${code} signal=${signal??'none'}\n${stderr}`);return {file:outPath,stderr,toolchain};}
export async function exportLeanModuleArtifact(options:ExportModuleArtifactOptions):Promise<{readonly artifact:ModuleArtifact;readonly toolchain:LeanToolchain}>{const {artifactModule,dependencies=[],metadata,maxBytes,...exportOptions}=options;if(artifactModule.length===0)fail('artifactModule is required');const collected=await collectLeanExport(exportOptions,maxBytes===undefined?{}:{maxBytes});return {artifact:createModuleArtifact({module:artifactModule,declarations:collected.text,dependencies,kernel:{semantics:'lean4',leanVersion:collected.toolchain.version,apiVersion:'0.1.0'},...(metadata===undefined?{}:{metadata})}),toolchain:collected.toolchain};}
export function defaultDependencyExporterPath(repoRoot=process.cwd()):string{return join(resolve(repoRoot),'oracle','replay-probe','DependencyExport.lean');}
