import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {buildChecked,defaultCheckedSeed} from './checked-build.mjs';
const seed=process.env.PSC2_CHECKED_SEED_BIN??defaultCheckedSeed;
const optionLean='inductive OwnedOption (a : Type) where\n  | none\n  | some (value : a)\ndef choose (choice : OwnedOption Nat) : Nat :=\n  match choice with\n  | OwnedOption.none => 0\n  | OwnedOption.some value => value\ndef answer : Nat := choose (OwnedOption.some 11)\n';
const optionPs="inductive OwnedOption(a : Type) where {\n  | none\n  | some(value : a)\n}\ndef choose(choice : OwnedOption(Nat)) : Nat := match choice with {\n  | OwnedOption.none => 0\n  | OwnedOption.some value => value\n}\ndef answer : Nat := choose(OwnedOption.some(11))\n";
const listLean='inductive OwnedList (a : Type) where\n  | nil\n  | cons (head : a) (tail : OwnedList a)\ndef count (xs : OwnedList Nat) : Nat :=\n  match xs with\n  | OwnedList.nil => 0\n  | OwnedList.cons head tail => Nat.succ (count tail)\ndef answer : Nat := count (OwnedList.cons 7 (OwnedList.cons 11 OwnedList.nil))\n';
const listPs="inductive OwnedList(a : Type) where {\n  | nil\n  | cons(head : a, tail : OwnedList(a))\n}\ndef count(xs : OwnedList(Nat)) : Nat := match xs with {\n  | OwnedList.nil => 0\n  | OwnedList.cons head tail => Nat.succ(count(tail))\n}\ndef answer : Nat := count(OwnedList.cons(7, OwnedList.cons(11, OwnedList.nil)))\n";
for(const [label,lean,ps,answer]of [['option',optionLean,optionPs,11n],['recursive-list',listLean,listPs,2n]])for(const kind of ['lean','ps'])test('real '+kind+' '+label+' is owned-checked, emitted and executed',{skip:!existsSync(seed)},async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'psc2-owned-algebraic-'));try{await writeFile(path.join(dir,'package.json'),'{"type":"module"}');const entryPath=path.join(dir,'Main.'+kind),outputPath=path.join(dir,'out.js');await writeFile(entryPath,kind==='lean'?lean:ps);
 const receipt=await buildChecked({entryPath,outputPath,seedPath:seed});assert.equal(receipt.kernel.selector,'pskernel-core');assert.equal(receipt.provider.profile,'owned-uniform-algebraic/11');assert.equal((await import(pathToFileURL(outputPath).href)).answer,answer);
 const input=JSON.parse(await readFile(path.join(dir,'out.admissions.json'),'utf8'));assert(input.admissions.some(x=>x.kind==='inductive'&&x.declaration.np===1));
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('bad parameterized branch cannot emit output or select another checker',{skip:!existsSync(seed)},async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'psc2-owned-algebraic-reject-'));try{const entryPath=path.join(dir,'Main.lean'),outputPath=path.join(dir,'never/out.js');await writeFile(entryPath,optionLean.replace('OwnedOption.none => 0','OwnedOption.none => OwnedOption.none'));await assert.rejects(buildChecked({entryPath,outputPath,seedPath:seed}));assert.equal(existsSync(path.dirname(outputPath)),false);}finally{await rm(dir,{recursive:true,force:true});}
});
