import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {checkOwnedAdmissions} from './checked-owned-kernel.mjs';import {checkAdmissionsWithKernel} from './checked-kernel-provider.mjs';import {definition} from '../packages/pskernel-core.old3/test/unit-values.mjs';
import {sum,value,eliminate,resultWitness,wireBatch,C,U,Z,S,B,pi,lam,literal,member} from '../packages/pskernel-core.old3/test/sum-values.mjs';
const raw=gunzipSync(readFileSync(new URL('../docs/continuity/owned-record-fields-2026-10-03/preserved75-admissions.json.gz',import.meta.url))).toString('utf8');assert.equal(createHash('sha256').update(raw).digest('hex'),'20715347d21c3151b02207cb0b17e4827fa098c1c97861c6438df79b2863a722');const original=JSON.parse(raw),selected={...original,admissions:[...original.admissions.slice(0,3),original.admissions[17]]};
test('exact PsLexError plus its checked record dependencies admits without claiming the full prefix',async()=>{const r=await checkOwnedAdmissions(JSON.stringify(selected));assert.equal(r.accepted,true,JSON.stringify(r));assert.equal(r.admissionCount,4);assert.equal(r.profile,'owned-uniform-algebraic/11');});
test('production sum boundary proves computed payload-result equality',async()=>{
 const e=sum('S',[[C('Nat'),C('Nat')],[]]),term=eliminate(e,0,[literal(2),literal(3)],[lam('a',C('Nat'),lam('b',C('Nat'),B(1))),literal(0)]);
 for(const [n,accepted]of [[2,true],[3,false]]){const w=resultWitness(term,n),{result,descriptor}=await checkAdmissionsWithKernel(wireBatch([e,definition('Witness',[],w.type,w.value)]),'pskernel-core.old3');assert.equal(descriptor.selector,'pskernel-core.old3');assert.equal(result.accepted,accepted,JSON.stringify(result));}
});
for(const [label,change]of [['forged family metadata',d=>{d.ts[0].fields=0;}],['forged constructor metadata',d=>{d.ts[0].cs[0].recursive=true;}],['parameters',d=>{d.np=1;}],['mutual family',d=>{d.ts.push(d.ts[0]);}],['universe parameters',d=>{d.lp=[{k:'s',p:{k:'a'},v:'u'}];}],['Prop family',d=>{d.ts[0].t={k:'sort',l:{k:'z'}};}],['duplicate constructor',d=>{d.ts[0].cs[1].n=d.ts[0].cs[0].n;}],['wrong constructor result',d=>{d.ts[0].cs[0].t={k:'const',n:{k:'s',p:{k:'a'},v:'Nat'},ls:[]};}]])test('owned sum boundary rejects '+label,async()=>{
 const input=JSON.parse(wireBatch([sum('S',[[C('Nat')],[]])]));change(input.admissions[0].declaration);const r=await checkOwnedAdmissions(JSON.stringify(input));assert.equal(r.accepted,false,JSON.stringify(r));assert.equal(r.admissionIndex,0);assert.equal(r.environment,undefined);
});
test('production sum rejection cannot discard invalid fields or retain partial authority',async()=>{
 const e=sum('S',[[C('Nat'),C('Nat')],[]]),term=eliminate(e,0,[literal(2),U(Z)],[lam('a',C('Nat'),lam('b',C('Nat'),B(1))),literal(0)]),r=await checkOwnedAdmissions(wireBatch([e,definition('Bad',[],C('Nat'),term)]));assert.equal(r.accepted,false);assert.equal(r.admissionIndex,1);assert.equal(r.environment,undefined);
 assert.equal((await checkOwnedAdmissions(wireBatch([e]))).accepted,true);assert.equal((await checkOwnedAdmissions(wireBatch([definition('Leak',[],C('S'),value(e,1))]))).accepted,false);
});
test('production sum shares one exact budget with the Nat bootstrap and all declarations',async()=>{const input=JSON.stringify(selected),r=await checkOwnedAdmissions(input);assert.equal(r.accepted,true);const short=await checkOwnedAdmissions(input,{maxSteps:r.steps-1});assert.equal(short.accepted,false);assert.equal(short.errorKind,'outOfFuel');assert.equal(short.environment,undefined);assert.equal((await checkOwnedAdmissions(input,{maxSteps:r.steps})).accepted,true);});
