import Ps.BackendJs.Model
import Ps.Bridge.Json

def psJsEmitLiteral (value : PsJsLiteral) : String :=
  match value with
  | PsJsLiteral.natural number => psJsonConcat2 (toString number) "n"
  | PsJsLiteral.integer number => psJsonConcat2 (toString number) "n"
  | PsJsLiteral.boolean boolean => if boolean then "true" else "false"
  | PsJsLiteral.string text => psJsonQuote text
  | PsJsLiteral.undefined => "undefined"

def psJsLocalName (index : Nat) : String :=
  psJsonConcat2 "__psc_js_l_" (toString index)

def psJsEmitParameterNames (parameters : List Nat) : String :=
  match parameters with
  | List.nil => ""
  | List.cons index rest =>
      match rest with
      | List.nil => psJsLocalName index
      | List.cons _ _ =>
          psJsonConcat3
            (psJsLocalName index)
            ", "
            (psJsEmitParameterNames rest)

def psJsEmitExpr (expr : PsJsExpr) : String :=
  match expr with
  | PsJsExpr.literal value => psJsEmitLiteral value
  | PsJsExpr.local index => psJsLocalName index
  | PsJsExpr.letE index value body =>
      let name := psJsLocalName index;
      let start := psJsonConcat3 "((" name ") => ";
      let withBody := psJsonConcat3 start (psJsEmitExpr body) ")(";
      psJsonConcat3 withBody (psJsEmitExpr value) ")"
  | PsJsExpr.lambda parameters body =>
      let names := psJsEmitParameterNames parameters;
      let start := psJsonConcat3 "((" names ") => ";
      psJsonConcat3 start (psJsEmitExpr body) ")"

def psJsEmitConstants (constants : List PsJsConstant) : Nat -> String :=
  match constants with
  | List.nil => fun (_index : Nat) => ""
  | List.cons constant rest =>
      let smaller : Nat -> String := psJsEmitConstants rest;
      fun (index : Nat) =>
        let internalName := psJsonConcat2 "__psc_js_" (toString index);
        let definition := psJsonConcat3 "const " internalName " = ";
        let value := psJsonConcat3 definition (psJsEmitExpr constant.body) ";\n";
        let exportStart := psJsonConcat3 "export { " internalName " as ";
        let exportLine := psJsonConcat3 exportStart constant.exportName " };\n";
        psJsonConcat3 value exportLine (smaller (Nat.succ index))

def psJsEmitTargetModule (module : PsJsModule) : String :=
  psJsonConcat2
    "// Generated by ProofScript backend-js (lexical profile).\nexport {};\n"
    (psJsEmitConstants module.constants 0)
