import Ps.BackendJs.Model
import Ps.Bridge.Json

def psJsEmitLiteral (value : PsJsLiteral) : String :=
  match value with
  | PsJsLiteral.natural number => psJsonConcat2 (toString number) "n"
  | PsJsLiteral.integer number => psJsonConcat2 (toString number) "n"
  | PsJsLiteral.boolean boolean => if boolean then "true" else "false"
  | PsJsLiteral.string text => psJsonQuote text
  | PsJsLiteral.undefined => "undefined"

def psJsEmitConstants (constants : List PsJsConstant) : Nat -> String :=
  match constants with
  | List.nil => fun (_index : Nat) => ""
  | List.cons constant rest =>
      let smaller : Nat -> String := psJsEmitConstants rest;
      fun (index : Nat) =>
        let internalName := psJsonConcat2 "__psc_js_" (toString index);
        let definition := psJsonConcat3 "const " internalName " = ";
        let value := psJsonConcat3 definition (psJsEmitLiteral constant.value) ";\n";
        let exportStart := psJsonConcat3 "export { " internalName " as ";
        let exportLine := psJsonConcat3 exportStart constant.exportName " };\n";
        psJsonConcat3 value exportLine (smaller (Nat.succ index))

def psJsEmitTargetModule (module : PsJsModule) : String :=
  psJsonConcat2
    "// Generated by ProofScript backend-js (literal profile).\nexport {};\n"
    (psJsEmitConstants module.constants 0)
