import BackendJsFixture
import BackendJsTailFixture
import Ps.BackendJs.Print

def psBackendJsExpected : String :=
  "// generated by ProofScript direct JsIR v1\n" ++
  "import { importedAdd as externalAdd } from \"./support.js\";\n" ++
  "import { namedIdentity } from \"./support.js\";\n" ++
  "import { default as externalDefault } from \"./support.js\";\n" ++
  "let __ps$utf8Cache;\nfunction __ps$utf8(source) { if (__ps$utf8Cache?.source === source) return __ps$utf8Cache; const entries = new Map(); let size = 0n; for (const char of source) { const cp = char.codePointAt(0) ?? 0; const width = BigInt(cp <= 0x7f ? 1 : cp <= 0x7ff ? 2 : cp <= 0xffff ? 3 : 4); entries.set(size, [char, width]); size += width; } return (__ps$utf8Cache = { source, entries, size }); }\n" ++
  "export const answer = 42n;\n" ++
  "export function idNat(x) { return x; }\n" ++
  "export function plusOne(x) { return (x + 1n); }\n" ++
  "export function choose(flag, left, right) { return (flag ? left : right); }\n" ++
  "export function callPlusOne(x) { return plusOne(x); }\n" ++
  "export const greeting = \"hello\";\n" ++
  "export const truth = true;\n" ++
  "export const unitValue = (void 0);\n" ++
  "export function natSubDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_a >= __ps_b ? __ps_a - __ps_b : 0n))(left, right); }\n" ++
  "export function natDivDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? 0n : __ps_a / __ps_b))(left, right); }\n" ++
  "export function natModDemo(left, right) { return ((__ps_a, __ps_b) => (__ps_b === 0n ? __ps_a : __ps_a % __ps_b))(left, right); }\n" ++
  "export function intNegDemo(value) { return (-(value)); }\n" ++
  "export function boolAndDemo(left, right) { return (left && right); }\n" ++
  "export function stringLengthDemo(value) { return ((__ps_s) => BigInt(Array.from(__ps_s).length))(value); }\n" ++
  "export function stringUtf8ByteSizeDemo(value) { return __ps$utf8(value).size; }\n" ++
  "export function stringNextDemo(value, position) { return ((__ps_s, __ps_p) => __ps_p + (__ps$utf8(__ps_s).entries.get(__ps_p)?.[1] ?? 1n))(value, position); }\n" ++
  "export function stringGetDemo(value, position) { return ((__ps_s, __ps_p) => __ps$utf8(__ps_s).entries.get(__ps_p)?.[0] ?? \"A\")(value, position); }\n" ++
  "export function stringAtEndDemo(value, position) { return ((__ps_s, __ps_p) => __ps_p >= __ps$utf8(__ps_s).size)(value, position); }\n" ++
  "export function stringExtractDemo(value, start, stop) { return ((__ps_s, __ps_b, __ps_e) => { if (__ps_b >= __ps_e) return \"\"; let __ps_i = 0n; let __ps_started = false; let __ps_out = \"\"; for (const __ps_c of __ps_s) { const __ps_cp = __ps_c.codePointAt(0) ?? 0; const __ps_w = BigInt(__ps_cp <= 0x7f ? 1 : __ps_cp <= 0x7ff ? 2 : __ps_cp <= 0xffff ? 3 : 4); if (!__ps_started) { if (__ps_i === __ps_b) __ps_started = true; else { __ps_i += __ps_w; continue; } } if (__ps_i === __ps_e) return __ps_out; __ps_out += __ps_c; __ps_i += __ps_w; } return __ps_out; })(value, start, stop); }\n" ++
  "export function arrayEmptyDemo(capacity) { return (() => { void (capacity); return []; })(); }\n" ++
  "export function arraySizeDemo(array) { return BigInt((array).length); }\n" ++
  "export function arrayPushDemo(array, value) { return [...(array), value]; }\n" ++
  "export function arrayGetDemo(array, index) { return ((__ps_a, __ps_i) => __ps_a[Number(__ps_i)])(array, index); }\n" ++
  "export function arrayGetDDemo(array, index, fallback) { return ((__ps_a, __ps_i, __ps_fallback) => (__ps_i < BigInt(__ps_a.length) ? __ps_a[Number(__ps_i)] : __ps_fallback))(array, index, fallback); }\n" ++
  "export function arraySetDemo(array, index, value) { return ((__ps_a, __ps_i, __ps_v) => { const __ps_out = [...__ps_a]; __ps_out[Number(__ps_i)] = __ps_v; return __ps_out; })(array, index, value); }\n" ++
  "export function arraySetIfInBoundsDemo(array, index, value) { return ((__ps_a, __ps_i, __ps_v) => { if (__ps_i >= BigInt(__ps_a.length)) return __ps_a; const __ps_out = [...__ps_a]; __ps_out[Number(__ps_i)] = __ps_v; return __ps_out; })(array, index, value); }\n" ++
  "export function arrayMapDemo(fn, array) { return ((__ps_f, __ps_a) => __ps_a.map((__ps_x) => __ps_f(__ps_x)))(fn, array); }\n" ++
  "export function arrayFoldDemo(fn, init, array, start, stop) { return ((__ps_f, __ps_init, __ps_a, __ps_start, __ps_stop) => { const __ps_size = BigInt(__ps_a.length); const __ps_end = __ps_stop <= __ps_size ? __ps_stop : __ps_size; let __ps_acc = __ps_init; for (let __ps_i = __ps_start; __ps_i < __ps_end; __ps_i += 1n) { __ps_acc = __ps_f(__ps_acc, __ps_a[Number(__ps_i)]); } return __ps_acc; })(fn, init, array, start, stop); }\n" ++
  "export function externalAddDemo(left, right) { return externalAdd(left, right); }\n" ++
  "export function externalNamedDemo(value) { return namedIdentity(value); }\n" ++
  "export function externalDefaultDemo(value) { return externalDefault(value); }\n" ++
  "export function genericIdNat(value) { return genericId$spec$Nat(value); }\n" ++
  "export function pointSum(left, right) { return ((point) => ((point)[\"x\"] + (point)[\"y\"]))(({ [\"x\"]: left, [\"y\"]: right })); }\n" ++
  "export function boxNatGet(value) { return ((box) => (box)[\"value\"])(({ [\"value\"]: value })); }\n" ++
  "export function maybeSomeOrZero(value) { return ((__ps$match$0) => { switch (__ps$match$0[\"$ps$tag\"]) { case \"none\": { return 0n; } case \"some\": { const payload = __ps$match$0[\"$ps$fields\"][\"value\"]; return payload; } } throw new Error(\"invalid ProofScript constructor tag\"); })(({ \"$ps$tag\": \"some\", \"$ps$fields\": { [\"value\"]: value } })); }\n" ++
  "export function maybeNoneOr(fallback) { return ((__ps$match$0) => { switch (__ps$match$0[\"$ps$tag\"]) { case \"none\": { return fallback; } case \"some\": { const payload = __ps$match$0[\"$ps$fields\"][\"value\"]; return payload; } } throw new Error(\"invalid ProofScript constructor tag\"); })(({ \"$ps$tag\": \"none\", \"$ps$fields\": {  } })); }\n" ++
  "export function optionNatSome(value) { return ((__ps$match$0) => { switch (__ps$match$0[\"$ps$tag\"]) { case \"none\": { return 0n; } case \"some\": { const payload = __ps$match$0[\"$ps$fields\"][\"value\"]; return payload; } } throw new Error(\"invalid ProofScript constructor tag\"); })(({ \"$ps$tag\": \"some\", \"$ps$fields\": { [\"value\"]: value } })); }\n" ++
  "export function matchTempCollision(__ps$match$0, value) { return ((__ps$match$1) => { switch (__ps$match$1[\"$ps$tag\"]) { case \"none\": { return __ps$match$0; } case \"some\": { const payload = __ps$match$1[\"$ps$fields\"][\"value\"]; return (__ps$match$0 + payload); } } throw new Error(\"invalid ProofScript constructor tag\"); })(({ \"$ps$tag\": \"some\", \"$ps$fields\": { [\"value\"]: value } })); }\n" ++
  "export function u8AddWrap(left, right) { return (((left + right)) & 255); }\n" ++
  "export function i8MulWrap(left, right) { return (((Math.imul(left, right)) << 24) >> 24); }\n" ++
  "export function u64Xor(left, right) { return BigInt.asUintN(64, ((left ^ right))); }\n" ++
  "export function u16Lt(left, right) { return (left < right); }\n" ++
  "export function u8FromNat(value) { return Number(BigInt.asUintN(8, value)); }\n" ++
  "export const u8Literal44 = Number(BigInt.asUintN(8, 44n));\n" ++
  "export function float32Mul(left, right) { return Math.fround((left * right)); }\n" ++
  "export function floatDiv(left, right) { return (left / right); }\n" ++
  "export function letNatDemo(x) { return ((y) => (y * 2n))((x + 1n)); }\n" ++
  "export function applyLambda(x) { return ((y) => (y + 2n))(x); }\n" ++
  "export function genericId$spec$Nat(x) { return x; }\n"

def psTestBackendJsFixtureEmission : Bool :=
  match psBackendJsFixtureValidated with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error _ => false
      | Except.ok output =>
          output == psBackendJsExpected

def psBackendJsKeywordModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "class"
        typeParameters := []
        parameters := []
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.literal
            (PsVerifiedIrLiteral.natural 1)
      }
    ]
  }

def psTestBackendJsRejectsKeywordName : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsKeywordModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            (PsJsLowerError.unsupportedName name)) =>
          psStringEq name "class"
      | _ => false

def psBackendJsStructureModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := [
      {
        name := "Box"
        typeParameters := []
        fields := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.nat
          }
        ]
      }
    ]
    inductives := []
    declarations := []
  }

def psTestBackendJsAcceptsStructureMetadata : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsStructureModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error _ => false
      | Except.ok output =>
          psStringEq
            output
            (String.Internal.append "// generated by ProofScript direct JsIR v1\n" psJsStringRuntimeSupport)

def psBackendJsUnsupportedIntrinsicModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "utf8Size"
        typeParameters := []
        parameters := [
          {
            name := "value"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.string
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.nat
        body :=
          PsVerifiedIrExpr.intrinsic
            PsVerifiedIrIntrinsic.stringUtf8ByteSize
            []
            [PsVerifiedIrExpr.var "value"]
      }
    ]
  }

def psTestBackendJsRejectsUnsupportedIntrinsic : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsUnsupportedIntrinsicModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedIntrinsic) =>
          true
      | _ => false

def psBackendJsWordSizedModule : PsVerifiedIrModule :=
  {
    imports := []
    structures := []
    inductives := []
    declarations := [
      {
        name := "wordAdd"
        typeParameters := []
        parameters := [
          {
            name := "left"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          },
          {
            name := "right"
            type :=
              PsVerifiedIrType.primitive
                PsVerifiedIrPrimitiveType.usize
          }
        ]
        resultType :=
          PsVerifiedIrType.primitive
            PsVerifiedIrPrimitiveType.usize
        body :=
          PsVerifiedIrExpr.intrinsic
            (PsVerifiedIrIntrinsic.machineIntBinary
              PsVerifiedIrMachineIntegerType.usize
              PsVerifiedIrIntegerBinaryOp.add)
            []
            [
              PsVerifiedIrExpr.var "left",
              PsVerifiedIrExpr.var "right"
            ]
      }
    ]
  }

def psTestBackendJsRejectsWordSizedWithoutProfile : Bool :=
  match
      psValidateErasedIrModule
        (PsErasedIrModule.mk
          psBackendJsWordSizedModule) with
  | Except.error _ => false
  | Except.ok validated =>
      match psJsEmitValidatedModule validated with
      | Except.error
          (PsJsEmitError.lower
            PsJsLowerError.unsupportedType) =>
          true
      | _ => false

def psTestBackendJsMachineIntegerPrinters : Bool :=
  psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint8
        300)
      "Number(BigInt.asUintN(8, 300n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int8
        200)
      "Number(BigInt.asIntN(8, 200n))"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.uint64
        5)
      "BigInt.asUintN(64, 5n)"
    && psStringEq
      (psJsPrintMachineIntegerLiteral
        PsJsIrMachineIntegerType.int64
        (-5))
      "BigInt.asIntN(64, -5n)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint8
        PsJsIrIntegerBinaryOp.add
        "left"
        "right")
      "(((left + right)) & 255)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint16
        PsJsIrIntegerBinaryOp.sub
        "left"
        "right")
      "(((left - right)) & 65535)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.int32
        PsJsIrIntegerBinaryOp.mul
        "left"
        "right")
      "((Math.imul(left, right)) | 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitAnd
        "left"
        "right")
      "(((left & right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint32
        PsJsIrIntegerBinaryOp.bitOr
        "left"
        "right")
      "(((left | right)) >>> 0)"
    && psStringEq
      (psJsPrintMachineIntegerBinary
        PsJsIrMachineIntegerType.uint64
        PsJsIrIntegerBinaryOp.bitXor
        "left"
        "right")
      "BigInt.asUintN(64, ((left ^ right)))"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintIntegerCompare
        PsJsIrIntegerCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsFloatPrinters : Bool :=
  psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.add
        "left"
        "right")
      "(left + right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.sub
        "left"
        "right")
      "(left - right)"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float32
        PsJsIrFloatBinaryOp.mul
        "left"
        "right")
      "Math.fround((left * right))"
    && psStringEq
      (psJsPrintFloatBinary
        PsJsIrFloatingType.float
        PsJsIrFloatBinaryOp.div
        "left"
        "right")
      "(left / right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.eq "left" "right")
      "(left === right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ne "left" "right")
      "(left !== right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.lt "left" "right")
      "(left < right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.le "left" "right")
      "(left <= right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.gt "left" "right")
      "(left > right)"
    && psStringEq
      (psJsPrintFloatCompare
        PsJsIrFloatCompareOp.ge "left" "right")
      "(left >= right)"

def psTestBackendJsUInt8OfNatPrinter : Bool :=
  match
      psJsRuntimeUnary
        PsJsIrRuntimeOp.uint8OfNat
        "value" with
  | Except.ok printed =>
      psStringEq
        printed
        "Number(BigInt.asUintN(8, value))"
  | Except.error _ => false

def psBackendJsSelectiveStackModule : PsJsIrModule :=
  {
    imports := []
    declarations := [
      {
        name := "helper"
        parameters := [{ name := "x" }]
        body := PsJsIrExpr.var "x"
      },
      {
        name := "recur"
        parameters := [{ name := "n" }]
        body :=
          PsJsIrExpr.call
            (PsJsIrExpr.var "helper")
            [
              PsJsIrExpr.call
                (PsJsIrExpr.var "recur")
                [PsJsIrExpr.var "n"]
            ]
      }
    ]
  }

def psTestBackendJsSelectiveStackSafety : Bool :=
  match psJsPrintModuleStackSafe psBackendJsSelectiveStackModule with
  | Except.error _ => false
  | Except.ok output =>
      let recursionSafe : Bool :=
        output.contains "__ps$invoke(recur, n)"
          || output.contains "while (true)";
      let helperNotTrampolined : Bool :=
        !output.contains "__ps$impl$helper";
      recursionSafe && helperNotTrampolined

def psBackendJsTailLoopModule : PsJsIrModule :=
  {
    imports := []
    declarations := [
      {
        name := "tail"
        parameters := [{ name := "n" }]
        body :=
          PsJsIrExpr.call
            (PsJsIrExpr.var "tail")
            [PsJsIrExpr.var "n"]
      }
    ]
  }

def psTestBackendJsTailLoop : Bool :=
  match psJsPrintModuleStackSafe psBackendJsTailLoopModule with
  | Except.error _ => false
  | Except.ok output =>
      output.contains
        "export function tail(n) { let __ps$tail$state = [n]; while (true) { const [n] = __ps$tail$state; __ps$tail$state = [n]; continue; } }"
        && !output.contains "function* __ps$impl$tail"


def psBackendJsNestedTailMatchModule : PsJsIrModule :=
  {
    imports := []
    declarations := [
      {
        name := "walk"
        parameters := [{ name := "value" }]
        body :=
          PsJsIrExpr.matchE
            (PsJsIrExpr.var "value")
            [
              (
                "done",
                [],
                PsJsIrExpr.literal
                  (PsJsIrLiteral.natural 0)
              ),
              (
                "more",
                [
                  {
                    field := "next"
                    name := "next"
                  }
                ],
                PsJsIrExpr.matchE
                  (PsJsIrExpr.var "next")
                  [
                    (
                      "done",
                      [],
                      PsJsIrExpr.literal
                        (PsJsIrLiteral.natural 0)
                    ),
                    (
                      "more",
                      [
                        {
                          field := "next"
                          name := "next2"
                        }
                      ],
                      PsJsIrExpr.call
                        (PsJsIrExpr.var "walk")
                        [PsJsIrExpr.var "next2"]
                    )
                  ]
              )
            ]
      }
    ]
  }

def psTestBackendJsNestedTailMatchHygiene : Bool :=
  match
      psJsPrintModuleStackSafe
        psBackendJsNestedTailMatchModule with
  | Except.error _ => false
  | Except.ok output =>
      output.contains "const __ps$tail$match$0"
        && output.contains "const __ps$tail$match$1"
        && output.contains
          "__ps$tail$state = [next2]; continue;"


def psTestBackendJsTextJoin : Bool :=
  let lengths : List Nat := [0, 1, 2, 3, 4, 7, 8, 9, 31, 32, 33, 1025]
  lengths.all fun count =>
    let chunks : List String := (List.range count).map fun index =>
      if index % 3 == 0 then "" else "λ😀:" ++ toString index
    ["", ", ", "界"].all fun separator =>
      psTextJoin separator chunks == String.intercalate separator chunks

def psTestBackendJsTextPersistence : Bool :=
  let first := psTextBuilderAppend psTextBuilderEmpty "first"
  let second := psTextBuilderAppend first "λ"
  let third := psTextBuilderAppend second "😀"
  psTextBuilderFinish first == "first" &&
    psTextBuilderFinish second == "firstλ" &&
    psTextBuilderFinish third == "firstλ😀"

def psBackendJsWriterDeclarations : List PsJsIrDeclaration := [
  { name := "first", parameters := [], body := PsJsIrExpr.literal (PsJsIrLiteral.natural 1) },
  { name := "second", parameters := [], body := PsJsIrExpr.literal (PsJsIrLiteral.natural 2) },
  { name := "third", parameters := [], body := PsJsIrExpr.literal (PsJsIrLiteral.natural 3) }
]

def psTestBackendJsWriterOrder : Bool :=
  let expected := "export const first = 1n;\nexport const second = 2n;\nexport const third = 3n;\n"
  match psJsPrintDeclarations psBackendJsWriterDeclarations with
  | Except.error _ => false
  | Except.ok ordinary =>
      match psJsPrintDeclarationsStackSafe psBackendJsWriterDeclarations with
      | Except.error _ => false
      | Except.ok stackSafe => ordinary == expected && stackSafe == expected

def psTestBackendJsWriterFirstError : Bool :=
  let reject : PsJsIrDeclaration -> Except PsJsEmitError String :=
    fun declaration =>
      if declaration.name == "first" then Except.error PsJsEmitError.malformedIr
      else Except.error PsJsEmitError.fuelExhausted
  match psJsPrintDeclarationsWith reject psBackendJsWriterDeclarations psTextBuilderEmpty with
  | Except.error PsJsEmitError.malformedIr => true
  | _ => false

structure PsBackendJsNamedTest where
  name : String
  passed : Bool

def psBackendJsTests : List PsBackendJsNamedTest := [
  { name := "portable text join boundaries and Unicode", passed := psTestBackendJsTextJoin },
  { name := "persistent text builder snapshots", passed := psTestBackendJsTextPersistence },
  { name := "normal and stack-safe writer declaration order", passed := psTestBackendJsWriterOrder },
  { name := "writer preserves first diagnostic", passed := psTestBackendJsWriterFirstError },
  { name := "removed worker aliases cannot be captured as values", passed := psJsTailFixtureCapturedAliasDeclined },
  { name := "fixture emission", passed := psTestBackendJsFixtureEmission },
  { name := "UTF-8 runtime name rejection", passed := !psJsIdentifierSupported "__ps$utf8" && !psJsIdentifierSupported "__ps$utf8Cache" },
  { name := "keyword rejection", passed := psTestBackendJsRejectsKeywordName },
  { name := "structure metadata", passed := psTestBackendJsAcceptsStructureMetadata },
  { name := "word-sized no-profile rejection", passed := psTestBackendJsRejectsWordSizedWithoutProfile },
  { name := "machine integer printers", passed := psTestBackendJsMachineIntegerPrinters },
  { name := "float printers", passed := psTestBackendJsFloatPrinters },
  { name := "UInt8.ofNat printer", passed := psTestBackendJsUInt8OfNatPrinter },
  { name := "selective stack safety", passed := psTestBackendJsSelectiveStackSafety },
  { name := "tail recursion loop", passed := psTestBackendJsTailLoop },
  { name := "nested tail-match hygiene", passed := psTestBackendJsNestedTailMatchHygiene }
]

def psRunBackendJsTests : List PsBackendJsNamedTest -> IO Bool
  | [] => pure true
  | test :: rest => do
      if test.passed then
        IO.println ("PSC2_BACKEND_JS_PASS: " ++ test.name)
      else
        IO.println ("PSC2_BACKEND_JS_FAIL: " ++ test.name)
      let restPassed ← psRunBackendJsTests rest
      pure (test.passed && restPassed)

def psReportBackendJsSelectiveStackSafety : IO Unit := do
  if psTestBackendJsSelectiveStackSafety then
    pure Unit.unit
  else
    match psJsPrintModuleStackSafe psBackendJsSelectiveStackModule with
    | Except.error _ =>
        IO.println "PSC2_BACKEND_JS_SELECTIVE_OUTPUT: <emit-error>"
    | Except.ok output =>
        IO.println
          ("PSC2_BACKEND_JS_SELECTIVE_OUTPUT_BEGIN\n" ++
            output ++
            "PSC2_BACKEND_JS_SELECTIVE_OUTPUT_END")

def main : IO Unit := do
  psReportBackendJsSelectiveStackSafety
  let passed ← psRunBackendJsTests psBackendJsTests
  if passed then
    IO.println "PSC2_BACKEND_JS_TESTS: PASS"
  else
    throw
      (IO.userError
        "PSC2_BACKEND_JS_TESTS: FAIL")
