export type BackendLiteral=null|boolean|string|number|bigint;
export type BackendExpr =
  | {readonly kind:'literal';readonly value:BackendLiteral}
  | {readonly kind:'var';readonly name:string}
  | {readonly kind:'lambda';readonly params:readonly string[];readonly body:BackendExpr}
  | {readonly kind:'call';readonly fn:BackendExpr;readonly args:readonly BackendExpr[]}
  | {readonly kind:'let';readonly name:string;readonly value:BackendExpr;readonly body:BackendExpr}
  | {readonly kind:'if';readonly cond:BackendExpr;readonly then:BackendExpr;readonly else:BackendExpr}
  | {readonly kind:'ctor';readonly tag:string;readonly fields:readonly BackendExpr[]};
export interface BackendBinding {readonly name:string;readonly value:BackendExpr}
export interface BackendModule {readonly name:string;readonly bindings:readonly BackendBinding[]}

const validName=/^[A-Za-z_$][A-Za-z0-9_$]*$/;
function name(value:string):string{
  if(!validName.test(value))throw new Error(`invalid JavaScript identifier '${value}'`);
  return value;
}
function literal(value:BackendLiteral):string{
  if(typeof value==='bigint')return `${value}n`;
  if(typeof value==='number'&&!Number.isFinite(value))throw new Error('non-finite backend literal');
  return JSON.stringify(value);
}
export function emitExpression(expr:BackendExpr):string{
  switch(expr.kind){
    case 'literal':return literal(expr.value);
    case 'var':return name(expr.name);
    case 'lambda':return `(${expr.params.map(name).join(', ')}) => ${emitExpression(expr.body)}`;
    case 'call':return `${emitExpression(expr.fn)}(${expr.args.map(emitExpression).join(', ')})`;
    case 'let':return `(() => { const ${name(expr.name)} = ${emitExpression(expr.value)}; return ${emitExpression(expr.body)}; })()`;
    case 'if':return `(${emitExpression(expr.cond)} ? ${emitExpression(expr.then)} : ${emitExpression(expr.else)})`;
    case 'ctor':return `({ tag: ${JSON.stringify(expr.tag)}, fields: [${expr.fields.map(emitExpression).join(', ')}] })`;
  }
}
export function emitModule(module:BackendModule):string{
  if(module.name.length===0)throw new Error('backend module name must be non-empty');
  const seen=new Set<string>();
  const lines=[`// generated by @proofscript/backend-ts from ${module.name}`];
  for(const binding of module.bindings){
    const bindingName=name(binding.name);
    if(seen.has(bindingName))throw new Error(`duplicate backend binding '${bindingName}'`);
    seen.add(bindingName);
    lines.push(`export const ${bindingName} = ${emitExpression(binding.value)};`);
  }
  return lines.join('\n')+'\n';
}
