import type {
  SoftwareIrExpr,
  SoftwareIrModule,
  SoftwareIrType,
} from '@proofscript/compiler-ir';

function typeScriptType(type:SoftwareIrType):string {
  switch(type){
    case 'Nat':
    case 'Int':return 'bigint';
    case 'Bool':return 'boolean';
    case 'String':return 'string';
    case 'Unit':return 'undefined';
  }
}

const PRECEDENCE:Readonly<Record<string,number>>={
  '||':1,'&&':2,'==':3,'!=':3,'<':4,'<=':4,'>':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6,
};

function emitNatTotalBinary(operator:string,left:string,right:string):string|undefined {
  if(operator==='-'){
    return '((__a, __b) => __a >= __b ? __a - __b : 0n)('+left+', '+right+')';
  }
  if(operator==='/'){
    return '((__a, __b) => __b === 0n ? 0n : __a / __b)('+left+', '+right+')';
  }
  if(operator==='%'){
    return '((__a, __b) => __b === 0n ? __a : __a % __b)('+left+', '+right+')';
  }
  return undefined;
}

export function emitSoftwareIrExpression(expr:SoftwareIrExpr,parentPrecedence=0):string {
  switch(expr.kind){
    case 'literal':
      if(expr.type==='Unit')return 'undefined';
      if(expr.type==='Nat'||expr.type==='Int')return String(expr.value)+'n';
      return JSON.stringify(expr.value);
    case 'var':return expr.name;
    case 'call':return expr.callee+'('+expr.args.map((arg)=>emitSoftwareIrExpression(arg)).join(', ')+')';
    case 'unary':return '!'+emitSoftwareIrExpression(expr.operand,7);
    case 'if':
      return '('+emitSoftwareIrExpression(expr.condition)+' ? '+emitSoftwareIrExpression(expr.thenBranch)+' : '+emitSoftwareIrExpression(expr.elseBranch)+')';
    case 'let':
      return '(() => { const '+expr.name+': '+typeScriptType(expr.bindingType)+' = '+emitSoftwareIrExpression(expr.value)+'; return '+emitSoftwareIrExpression(expr.body)+'; })()';
    case 'binary':{
      const left=emitSoftwareIrExpression(expr.left);
      const right=emitSoftwareIrExpression(expr.right);
      if(expr.type==='Nat'){
        const total=emitNatTotalBinary(expr.operator,left,right);
        if(total!==undefined)return total;
      }
      const operator=expr.operator==='=='?'===':expr.operator==='!='?'!==':expr.operator;
      const precedence=PRECEDENCE[expr.operator]??0;
      const rendered=emitSoftwareIrExpression(expr.left,precedence)+' '+operator+' '+emitSoftwareIrExpression(expr.right,precedence+1);
      return precedence<parentPrecedence?'('+rendered+')':rendered;
    }
  }
}

export function emitV061TypeScript(module:SoftwareIrModule):string {
  if(module.kind!=='proofscript-software-ir')throw new Error('PS_TS_EXPECTS_SOFTWARE_IR');
  const lines=['// generated by ProofScript; edit the .ps source instead'];
  for(const decl of module.declarations){
    if(decl.params.length===0){
      lines.push('export const '+decl.name+': '+typeScriptType(decl.resultType)+' = '+emitSoftwareIrExpression(decl.body)+';');
      continue;
    }
    const params=decl.params.map((param)=>param.name+': '+typeScriptType(param.type)).join(', ');
    lines.push('export function '+decl.name+'('+params+'): '+typeScriptType(decl.resultType)+' { return '+emitSoftwareIrExpression(decl.body)+'; }');
  }
  return lines.join('\n')+'\n';
}
