import type {
  SoftwareIrExpr,
  SoftwareIrModule,
  SoftwareIrType,
} from '@proofscript/compiler-ir';

function typeScriptType(type:SoftwareIrType):string {
  if(typeof type!=='string'){
    if(type.kind==='nominal')return type.name;
    return '(_arg: '+typeScriptType(type.parameter)+') => '+typeScriptType(type.result);
  }
  switch(type){
    case 'Nat':
    case 'Int':return 'bigint';
    case 'Bool':return 'boolean';
    case 'String':return 'string';
    case 'Unit':return 'undefined';
  }
}

function brandIdentifier(name:string):string {
  let hash=2166136261;
  for(let index=0;index<name.length;index+=1){
    hash^=name.charCodeAt(index);
    hash=Math.imul(hash,16777619);
  }
  const safe=name.replace(/[^A-Za-z0-9_$]/gu,'_');
  return '__ps_brand_'+(safe.length===0?'type':safe)+'_'+(hash>>>0).toString(16);
}

const PRECEDENCE:Readonly<Record<string,number>>={
  '||':1,'&&':2,'==':3,'!=':3,'<':4,'<=':4,'>':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6,
};

function emitNatTotalBinary(operator:string,left:string,right:string):string|undefined {
  if(operator==='-'){
    return '((__a, __b) => __a >= __b ? __a - __b : 0n)('+left+', '+right+')';
  }
  if(operator==='/'){
    return '((__a, __b) => __b === 0n ? 0n : __a / __b)('+left+', '+right+')';
  }
  if(operator==='%'){
    return '((__a, __b) => __b === 0n ? __a : __a % __b)('+left+', '+right+')';
  }
  return undefined;
}

export function emitSoftwareIrExpression(expr:SoftwareIrExpr,parentPrecedence=0):string {
  switch(expr.kind){
    case 'literal':
      if(expr.type==='Unit')return 'undefined';
      if(expr.type==='Nat'||expr.type==='Int')return String(expr.value)+'n';
      return JSON.stringify(expr.value);
    case 'var':return expr.name;
    case 'projection':return emitSoftwareIrExpression(expr.target)+'.'+expr.field;
    case 'record':{
      const brand=brandIdentifier(expr.structure);
      const fields=[
        '['+brand+']: true',
        ...expr.fields.map(
          (field)=>field.name+': '+emitSoftwareIrExpression(field.value),
        ),
      ];
      return '{ '+fields.join(', ')+' }';
    }
    case 'call':{
      if(expr.callStyle==='direct'){
        return expr.callee+'('+expr.args.map((arg)=>emitSoftwareIrExpression(arg)).join(', ')+')';
      }
      return expr.args.reduce(
        (callee,arg)=>callee+'('+emitSoftwareIrExpression(arg)+')',
        expr.callee,
      );
    }
    case 'match':{
      if(expr.alternatives.length===1&&expr.alternatives[0]?.pattern.kind==='wildcard'){
        const body=emitSoftwareIrExpression(expr.alternatives[0].body);
        return '((__match) => '+body+')('+emitSoftwareIrExpression(expr.scrutinee)+')';
      }
      const trueAlt=expr.alternatives.find(
        (alternative)=>alternative.pattern.kind==='bool'&&alternative.pattern.value,
      );
      const falseAlt=expr.alternatives.find(
        (alternative)=>alternative.pattern.kind==='bool'&&!alternative.pattern.value,
      );
      if(trueAlt===undefined||falseAlt===undefined){
        throw new Error('PS_TS_MATCH_UNSUPPORTED: expected exhaustive Bool alternatives');
      }
      return '('+emitSoftwareIrExpression(expr.scrutinee)+' ? '+
        emitSoftwareIrExpression(trueAlt.body)+' : '+emitSoftwareIrExpression(falseAlt.body)+')';
    }
    case 'lambda':{
      return [...expr.binders].reverse().reduce(
        (body,binder)=>'('+binder.name+': '+typeScriptType(binder.type)+') => '+body,
        emitSoftwareIrExpression(expr.body),
      );
    }
    case 'unary':return '!'+emitSoftwareIrExpression(expr.operand,7);
    case 'if':
      return '('+emitSoftwareIrExpression(expr.condition)+' ? '+emitSoftwareIrExpression(expr.thenBranch)+' : '+emitSoftwareIrExpression(expr.elseBranch)+')';
    case 'let':
      return '(() => { const '+expr.name+': '+typeScriptType(expr.bindingType)+' = '+emitSoftwareIrExpression(expr.value)+'; return '+emitSoftwareIrExpression(expr.body)+'; })()';
    case 'binary':{
      const left=emitSoftwareIrExpression(expr.left);
      const right=emitSoftwareIrExpression(expr.right);
      if(expr.type==='Nat'){
        const total=emitNatTotalBinary(expr.operator,left,right);
        if(total!==undefined)return total;
      }
      const operator=expr.operator==='=='?'===':expr.operator==='!='?'!==':expr.operator;
      const precedence=PRECEDENCE[expr.operator]??0;
      const rendered=emitSoftwareIrExpression(expr.left,precedence)+' '+operator+' '+emitSoftwareIrExpression(expr.right,precedence+1);
      return precedence<parentPrecedence?'('+rendered+')':rendered;
    }
  }
}

export function emitV061TypeScript(module:SoftwareIrModule):string {
  if(module.kind!=='proofscript-software-ir')throw new Error('PS_TS_EXPECTS_SOFTWARE_IR');
  const lines=['// generated by ProofScript; edit the .ps source instead'];
  for(const structure of module.structures){
    const brand=brandIdentifier(structure.name);
    lines.push(
      'const '+brand+': unique symbol = Symbol('+JSON.stringify('ProofScript.'+structure.name)+');',
    );
    lines.push('export interface '+structure.name+' {');
    lines.push('  readonly ['+brand+']: true;');
    for(const field of structure.fields){
      lines.push('  readonly '+field.name+': '+typeScriptType(field.type)+';');
    }
    lines.push('}');
  }
  for(const decl of module.declarations){
    if(decl.params.length===0){
      lines.push('export const '+decl.name+': '+typeScriptType(decl.resultType)+' = '+emitSoftwareIrExpression(decl.body)+';');
      continue;
    }
    const params=decl.params.map((param)=>param.name+': '+typeScriptType(param.type)).join(', ');
    lines.push('export function '+decl.name+'('+params+'): '+typeScriptType(decl.resultType)+' { return '+emitSoftwareIrExpression(decl.body)+'; }');
  }
  return lines.join('\n')+'\n';
}
