
import * as ts from 'typescript';

export type V061BackendType='Nat'|'Int'|'Bool'|'String'|'Unit';
export type V061BackendExpr =
  | {readonly kind:'nat';readonly value:bigint;readonly resultType:'Nat'|'Int'}
  | {readonly kind:'string';readonly value:string;readonly resultType:'String'}
  | {readonly kind:'bool';readonly value:boolean;readonly resultType:'Bool'}
  | {readonly kind:'unit';readonly resultType:'Unit'}
  | {readonly kind:'reference';readonly name:string;readonly resultType:V061BackendType}
  | {readonly kind:'call';readonly callee:string;readonly args:readonly V061BackendExpr[];readonly resultType:V061BackendType}
  | {readonly kind:'unary';readonly operator:'!';readonly operand:V061BackendExpr;readonly resultType:'Bool'}
  | {readonly kind:'binary';readonly operator:string;readonly left:V061BackendExpr;readonly right:V061BackendExpr;readonly resultType:V061BackendType}
  | {readonly kind:'if';readonly condition:V061BackendExpr;readonly thenBranch:V061BackendExpr;readonly elseBranch:V061BackendExpr;readonly resultType:V061BackendType};

export interface V061BackendDeclaration {
  readonly kind:'const'|'def'|'function';
  readonly name:string;
  readonly params:readonly {readonly name:string;readonly type:V061BackendType}[];
  readonly resultType:V061BackendType;
  readonly body:V061BackendExpr;
}
export interface V061BackendModule {
  readonly kind:'checked-v061-software-module';
  readonly declarations:readonly V061BackendDeclaration[];
}

function typeScriptType(type:V061BackendType):string {
  switch(type) {
    case 'Nat':
    case 'Int': return 'bigint';
    case 'Bool': return 'boolean';
    case 'String': return 'string';
    case 'Unit': return 'undefined';
  }
}

const PREC:Readonly<Record<string,number>>={
  '||':1,'&&':2,'==':3,'!=':3,'<':4,'<=':4,'>':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6,
};

function emitExpr(expr:V061BackendExpr,parentPrecedence=0):string {
  switch(expr.kind) {
    case 'nat': return String(expr.value)+'n';
    case 'string': return JSON.stringify(expr.value);
    case 'bool': return expr.value?'true':'false';
    case 'unit': return 'undefined';
    case 'reference': return expr.name;
    case 'call': return expr.callee+'('+expr.args.map((arg)=>emitExpr(arg)).join(', ')+')';
    case 'unary': return '!'+emitExpr(expr.operand,7);
    case 'if': return '('+emitExpr(expr.condition)+' ? '+emitExpr(expr.thenBranch)+' : '+emitExpr(expr.elseBranch)+')';
    case 'binary': {
      const left=emitExpr(expr.left);
      const right=emitExpr(expr.right);
      if(expr.resultType==='Nat'&&expr.operator==='-')return '(('+left+') >= ('+right+') ? ('+left+') - ('+right+') : 0n)';
      if(expr.resultType==='Nat'&&expr.operator==='/')return '(('+right+') === 0n ? 0n : ('+left+') / ('+right+'))';
      if(expr.resultType==='Nat'&&expr.operator==='%')return '(('+right+') === 0n ? ('+left+') : ('+left+') % ('+right+'))';
      const operator=expr.operator==='=='?'===':expr.operator==='!='?'!==':expr.operator;
      const precedence=PREC[expr.operator]??0;
      const rendered=emitExpr(expr.left,precedence)+' '+operator+' '+emitExpr(expr.right,precedence+1);
      return precedence<parentPrecedence?'('+rendered+')':rendered;
    }
  }
}

export function emitV061TypeScript(module:V061BackendModule):string {
  if(module.kind!=='checked-v061-software-module')throw new Error('PS_TS_EXPECTS_CHECKED_SOFTWARE_MODULE');
  const lines=['// generated by ProofScript; edit the .ps source instead'];
  for(const decl of module.declarations) {
    if(decl.params.length===0) {
      lines.push('export const '+decl.name+': '+typeScriptType(decl.resultType)+' = '+emitExpr(decl.body)+';');
      continue;
    }
    const params=decl.params.map((p)=>p.name+': '+typeScriptType(p.type)).join(', ');
    lines.push('export function '+decl.name+'('+params+'): '+typeScriptType(decl.resultType)+' { return '+emitExpr(decl.body)+'; }');
  }
  return lines.join('\n')+'\n';
}

export interface TypeScriptCompileResult {
  readonly javascript:string;
  readonly declaration:string;
  readonly sourceMap?:string;
  readonly diagnostics:readonly string[];
  readonly typescriptVersion:string;
}

export function compileTypeScript(source:string,fileName='module.ts'):TypeScriptCompileResult {
  const options:ts.CompilerOptions={
    target:ts.ScriptTarget.ES2022,
    module:ts.ModuleKind.ES2022,
    moduleResolution:ts.ModuleResolutionKind.Bundler,
    strict:true,
    declaration:true,
    sourceMap:true,
    noEmitOnError:true,
    skipLibCheck:true,
  };
  const defaultHost=ts.createCompilerHost(options);
  const outputs=new Map<string,string>();
  const host:ts.CompilerHost={
    ...defaultHost,
    fileExists:(name)=>name===fileName||defaultHost.fileExists(name),
    readFile:(name)=>name===fileName?source:defaultHost.readFile(name),
    getSourceFile:(name,languageVersion,onError,shouldCreateNewSourceFile)=>{
      if(name===fileName)return ts.createSourceFile(name,source,languageVersion,true,ts.ScriptKind.TS);
      return defaultHost.getSourceFile(name,languageVersion,onError,shouldCreateNewSourceFile);
    },
    writeFile:(name,text)=>{outputs.set(name,text);},
  };
  const program=ts.createProgram([fileName],options,host);
  const before=ts.getPreEmitDiagnostics(program);
  const emitted=program.emit();
  const diagnostics=[...before,...emitted.diagnostics].map((d)=>{
    const message=ts.flattenDiagnosticMessageText(d.messageText,'\n');
    if(d.file&&d.start!==undefined) {
      const pos=d.file.getLineAndCharacterOfPosition(d.start);
      return d.file.fileName+':'+(pos.line+1)+':'+(pos.character+1)+' TS'+d.code+': '+message;
    }
    return 'TS'+d.code+': '+message;
  });
  if(diagnostics.length>0)throw new Error('PS_TS_COMPILE_FAILED:\n'+diagnostics.join('\n'));

  const js=[...outputs.entries()].find(([name])=>name.endsWith('.js'))?.[1];
  const dts=[...outputs.entries()].find(([name])=>name.endsWith('.d.ts'))?.[1];
  const map=[...outputs.entries()].find(([name])=>name.endsWith('.js.map'))?.[1];
  if(js===undefined||dts===undefined)throw new Error('PS_TS_COMPILE_MISSING_OUTPUT');
  return {
    javascript:js,
    declaration:dts,
    ...(map===undefined?{}:{sourceMap:map}),
    diagnostics,
    typescriptVersion:ts.version,
  };
}
