import Ps.KernelCore.Metatheory.SemanticCheckedAnnotationVisits
import Ps.KernelCore.Metatheory.SemanticCheckedAnnotations
import Ps.KernelCore.Metatheory.SemanticUniverseRegime
import Ps.KernelCore.Metatheory.SemanticReferenceLambda
import Ps.KernelCore.Metatheory.SemanticFunctionValidity
import Ps.KernelCore.Metatheory.SemanticReference
import Ps.KernelCore.Metatheory.SemanticReferenceApplication
import Lean
import Ps.KernelCore.Metatheory.SemanticSortInference
import Ps.KernelCore.Metatheory.SemanticContext
import Ps.KernelCore.Metatheory.SemanticErasure
import Ps.KernelCore.Metatheory.SemanticModelAdequacy
import Ps.KernelCore.Metatheory.SemanticDeclarative
import Ps.KernelCore.Metatheory.SemanticConcrete
import Ps.KernelCore.Metatheory.SemanticExtension
import Ps.KernelCore.Metatheory.SemanticStructuralEquality
import Ps.KernelCore.Metatheory.SemanticAbstraction
import Ps.KernelCore.Metatheory.SemanticScope
import Ps.KernelCore.Metatheory.SemanticLevelConstructors
import Ps.KernelCore.Metatheory.SemanticUniverseSubstitution
import Ps.KernelCore.Metatheory.SemanticConstantInference

/-!
Machine-checked dependency audit for the new semantic foundation.
The allowlist is only the standard host foundation; sorryAx and every custom
axiom are rejected. Local domain and callback premises are separately exposed
in theorem statements and documented in RESEARCH_AND_MIGRATION.md.
-/

open Lean Elab Command in
run_cmd do
  let targets : Array Name := #[
    ``PsKernelSemantics.UniverseRegime.isNever_inter,
    ``PsKernelSemantics.UniverseRegime.isNever_ofLevel,
    ``PsKernelSemantics.UniverseRegime.native_positive_spec,
    ``PsKernelSemantics.Reference.beta_of_native_positive,
    ``PsKernelSemantics.UniverseRegime.same_regime_not_same_level,
    ``PsKernelSemantics.AnnotatedExpr.checkedExprEq_distinguishes_sorts,
    ``PsKernelSemantics.AnnotatedExpr.checkedExprEq_rejects_conflicting_lambdas,
    ``PsKernelSemantics.Reference.validateSortAnnotationWith_ok_iff,
    ``PsKernelSemantics.Reference.validateSortAnnotationWith_zero_mem,
    ``PsKernelSemantics.Reference.forall_trace_checked_sort,
    ``PsKernelSemantics.Reference.forall_trace_model_checked_annotation,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_refl,
    ``PsKernelSemantics.AnnotatedExpr.checkedExprEq_refl,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_liftN,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_instLevels,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_close,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_rejects_conflicting_lambdas,
    ``PsKernelSemantics.AnnotatedExpr.checkRegimes_rejects_conflicting_products,
    ``PsKernelSemantics.SetModel.checkRegimes_sound,
    ``PsKernelSemantics.SetModel.checkedExprEq_sound,
    ``PsKernelSemantics.SetModel.checkedExprEq_models_equal,
    ``PsKernelSemantics.SetModel.models_convert_checked,
    ``PsKernelSemantics.SetModel.checkedExprEq_substitution_sound,
    ``PsKernelSemantics.SetModel.checkedExprEq_instLevels_sound,
    ``PsKernelSemantics.UniverseRegime.holds_inter,
    ``PsKernelSemantics.UniverseRegime.ofLevel_spec,
    ``PsKernelSemantics.UniverseRegime.subset_spec,
    ``PsKernelSemantics.UniverseRegime.compare_spec,
    ``PsKernelSemantics.UniverseRegime.check_spec,
    ``PsKernelSemantics.UniverseRegime.check_refl,
    ``PsKernelSemantics.UniverseRegime.check_symm,
    ``PsKernelSemantics.UniverseRegime.check_trans,
    ``PsKernelSemantics.UniverseRegime.check_instParams,
    ``PsKernelSemantics.UniverseRegime.check_imax_right,
    ``PsKernelSemantics.UniverseRegime.check_max_comm,
    ``PsKernelSemantics.UniverseRegime.check_zero_succ,
    ``PsKernelSemantics.UniverseRegime.check_param_mvar,
    ``PsKernelSemantics.SetModel.hereditary_validity_not_erasure_coherence,
    ``PsKernelSemantics.SetModel.functionValid_withFree_fresh,
    ``PsKernelSemantics.SetModel.functionValid_close,
    ``PsKernelSemantics.SetModel.functionValid_inst_iff,
    ``PsKernelSemantics.SetModel.functionValid_open_fresh,
    ``PsKernelSemantics.Reference.inferCore_lam_trace,
    ``PsKernelSemantics.Reference.lambda_trace_model_from_visits,
    ``PsKernelSemantics.SetModel.functionValid_liftN,
    ``PsKernelSemantics.SetModel.functionValid_inst,
    ``PsKernelSemantics.SetModel.functionValid_inst_zero,
    ``PsKernelSemantics.SetModel.functionValid_instLevels,
    ``PsKernelSemantics.SetModel.functionValid_app_of_type,
    ``PsKernelSemantics.SetModel.functionValid_lam_of_type,
    ``PsKernelSemantics.SetModel.functionValid_beta_positive,
    ``PsKernelSemantics.SetModel.functionValid_beta_on_domain,
    ``PsKernelSemantics.SetModel.annotationValid_inst_iff,
    ``PsKernelSemantics.SetModel.annotationValid_open_fresh,
    ``PsKernelSemantics.Reference.ensureSort_mem,
    ``PsKernelSemantics.Reference.forall_trace_model_from_visits,
    ``PsKernelSemantics.SetModel.models_app_of_annotationValid,
    ``PsKernelSemantics.SetModel.models_beta_of_annotationValid,
    ``PsKernelSemantics.SetModel.application_result_annotationValid,
    ``PsKernelSemantics.Reference.inferCore_app_trace,
    ``PsKernelSemantics.Reference.applicationComparison_models_equal,
    ``PsKernelSemantics.Reference.application_trace_has_model,
    ``PsKernelSemantics.SetModel.annotationValid_withFree_fresh,
    ``PsKernelSemantics.SetModel.annotationValid_close,
    ``PsKernelSemantics.SetModel.annotationValidity_alone_not_coherence,
    ``PsKernelSemantics.Reference.ensureSort_result_sources,
    ``PsKernelSemantics.Reference.ensureSort_models_type,
    ``PsKernelSemantics.Reference.opened_sort_to_bound_sort,
    ``PsKernelSemantics.SetModel.annotationValid_forall_of_sort,
    ``PsKernelSemantics.SetModel.annotationValid_liftN,
    ``PsKernelSemantics.SetModel.annotationValid_inst,
    ``PsKernelSemantics.SetModel.annotationValid_inst_zero,
    ``PsKernelSemantics.SetModel.annotationValid_instLevels,
    ``PsKernelSemantics.SetModel.forged_product_annotation_invalid,
    ``PsKernelSemantics.Reference.inferCore_forall_trace,
    ``PsKernelSemantics.Reference.forall_trace_has_model,
    ``psKernelReferenceCacheGet_miss,
    ``psKernelReferenceCacheInsert_noop,
    ``psKernelReferenceCacheContains_miss,
    ``psKernelReferenceCacheInsertPair_noop,
    ``PsKernelSemantics.Reference.infer_publication_noop,
    ``PsKernelSemantics.Reference.equality_publication_noop,
    ``PsKernelSemantics.Reference.unfold_uncached,
    ``PsKernelSemantics.Reference.inferCore_sort_result,
    ``PsKernelSemantics.Reference.inferCore_const_result,
    ``PsKernelSemantics.Reference.sort_inference_has_set_model,
    ``PsKernelSemantics.Reference.const_inference_has_set_model,
    ``PsKernelSemantics.Interpretation.equal_symm,
    ``PsKernelSemantics.Interpretation.equal_trans,
    ``PsKernelSemantics.Interpretation.convert,
    ``PsKernelSemantics.Interpretation.proof_irrelevance,
    ``PsKernelSemantics.Interpretation.no_empty_inhabitant,
    ``PsKernelSemantics.Interpretation.not_equal_of_undefined,
    ``PsKernelSemantics.PropositionDomain.domain,
    ``PsKernelSemantics.PropositionDomain.pi_isProp,
    ``PsKernelSemantics.PropositionDomain.pi_intro,
    ``PsKernelSemantics.PropositionDomain.pi_elim,
    ``PsKernelSemantics.PropositionDomain.no_proof_of_all_props,
    ``PsKernelSemantics.PropositionDomain.sortValue_isType,
    ``PsKernelSemantics.PropositionDomain.sortValue_mem_succ,
    ``PsKernelSemantics.PropositionDomain.sortValue_not_mem_self,
    ``PsKernelSemantics.PropositionDomain.witness_propCompatible,
    ``PsKernelSemantics.PropositionDomain.witness_sort_hasType,
    ``PsKernelSemantics.PropositionDomain.witness_no_type_in_type,
    ``PsKernelSemantics.PropositionDomain.witness_proposition,
    ``PsKernelSemantics.PropositionDomain.witness_inhabited,
    ``PsKernelSemantics.PropositionDomain.witness_proof_irrelevance,
    ``PsKernelSemantics.PropositionDomain.witness_empty,
    ``PsKernelSemantics.PropositionDomain.witness_not_universal,
    ``PsKernelSemantics.PropositionDomain.undefined_not_equal,
    ``PsKernelSemantics.normalizesToZero_eval,
    ``PsKernelSemantics.checkedInference_implies_inferOnly,
    ``PsKernelSemantics.propCompatible_of_sort_valuation,
    ``PsKernelSemantics.classifier_true_sound,
    ``PsKernelSemantics.proofIrrelevance_calls_sound,
    ``PsKernelSemantics.PropositionDomain.forged_classifier_succeeds,
    ``PsKernelSemantics.PropositionDomain.proof_is_not_proposition,
    ``PsKernelSemantics.PropositionDomain.operational_success_is_insufficient,
    ``PsKernelSemantics.PropositionDomain.forgedInfer_not_sound,
    ``PsKernelSemantics.inferCore_sort_result,
    ``PsKernelSemantics.inferCore_sort_sound,
    ``PsKernelSemantics.sort_inference_has_concrete_model,
    ``PsKernelSemantics.SetModel.domain,
    ``PsKernelSemantics.SetModel.sort_isType,
    ``PsKernelSemantics.SetModel.sort_not_self,
    ``PsKernelSemantics.SetModel.pi_mem_sort,
    ``PsKernelSemantics.SetModel.application_mem,
    ``PsKernelSemantics.SetModel.beta,
    ``PsKernelSemantics.SetModel.eta,
    ``PsKernelSemantics.SetModel.empty_type_uninhabited,
    ``PsKernelSemantics.SetModel.no_proof_of_all_props,
    ``PsKernelSemantics.SetModel.interp_liftN,
    ``PsKernelSemantics.SetModel.interp_inst,
    ``PsKernelSemantics.SetModel.interp_inst_zero,
    ``PsKernelSemantics.SetModel.interp_scoped,
    ``PsKernelSemantics.SetModel.interp_closed,
    ``PsKernelSemantics.SetModel.models_sort,
    ``PsKernelSemantics.SetModel.models_forall,
    ``PsKernelSemantics.SetModel.models_lam,
    ``PsKernelSemantics.SetModel.models_app,
    ``PsKernelSemantics.SetModel.models_let,
    ``PsKernelSemantics.SetModel.models_convert,
    ``PsKernelSemantics.SetModel.models_proof_irrelevance,
    ``PsKernelSemantics.SetModel.models_beta,
    ``PsKernelSemantics.SetModel.models_zeta,
    ``PsKernelSemantics.SetModel.models_eta,
    ``PsKernelSemantics.SetModel.models_weaken,
    ``PsKernelSemantics.SetModel.empty_context_satisfiable,
    ``PsKernelSemantics.SetModel.no_closed_empty_type,
    ``PsKernelSemantics.SetModel.no_closed_allProps,
    ``PsKernelSemantics.AnnotatedExpr.erase_liftN,
    ``PsKernelSemantics.AnnotatedExpr.scoped_iff_noLoose,
    ``PsKernelSemantics.AnnotatedExpr.inst_scoped,
    ``PsKernelSemantics.AnnotatedExpr.erase_inst,
    ``PsKernelSemantics.AnnotatedExpr.erase_instantiate1,
    ``PsKernelSemantics.SetModel.instantiate1_has_reading,
    ``PsKernelSemantics.SetModel.propIdentity_scoped,
    ``PsKernelSemantics.SetModel.propIdentity_type,
    ``PsKernelSemantics.SetModel.propIdentityType_sort,
    ``PsKernelSemantics.SetModel.erasure_is_not_semantic_coherence,
    ``PsKernelSemantics.SetModel.models_variable_zero,
    ``PsKernelSemantics.SetModel.models_substitution,
    ``PsKernelSemantics.Declarative.sound,
    ``PsKernelSemantics.Declarative.identity_derives,
    ``PsKernelSemantics.Declarative.no_allProps,
    ``PsKernelSemantics.Declarative.no_empty,
    ``PsKernelSemantics.SetModel.sort_inference_has_set_model,
    ``PsKernelSemantics.SetModel.zeta_has_set_model,
    ``PsKernelSemantics.SetModel.substitution_has_typed_set_model,
    ``PsKernelSemantics.SetModel.beta_has_set_model,
    ``PsKernelSemantics.SetModel.interp_extendConstant,
    ``PsKernelSemantics.SetModel.satisfies_extendConstant,
    ``PsKernelSemantics.SetModel.modelsType_extendConstant,
    ``PsKernelSemantics.SetModel.newConstant_modelsType,
    ``PsKernelSemantics.SetModel.exprEq_preserves_interp,
    ``PsKernelSemantics.AnnotatedExpr.erase_close,
    ``PsKernelSemantics.AnnotatedExpr.erase_abstractFVar,
    ``PsKernelSemantics.SetModel.interp_withFree_fresh,
    ``PsKernelSemantics.SetModel.interp_close,
    ``PsKernelSemantics.SetModel.open_fresh_has_reading,
    ``PsKernelSemantics.SetModel.abstractFVar_has_reading,
    ``PsKernelSemantics.SetModel.abstractFVar_closed_input,
    ``PsKernelSemantics.AnnotatedExpr.scoped_mono,
    ``PsKernelSemantics.AnnotatedExpr.scoped_liftN,
    ``PsKernelSemantics.AnnotatedExpr.scoped_inst,
    ``PsKernelSemantics.AnnotatedExpr.scoped_close,
    ``PsKernelSemantics.AnnotatedExpr.namesBelow_fresh,
    ``PsKernelSemantics.AnnotatedExpr.allocator_fresh,
    ``PsKernelSemantics.AnnotatedExpr.opened_has_no_loose,
    ``PsKernelSemantics.AnnotatedExpr.closed_has_one_binder,
    ``PsKernelSemantics.SetModel.membership_is_not_annotation_coherence,
    ``PsKernelSemantics.isZero_eval,
    ``PsKernelSemantics.isNotZero_eval,
    ``PsKernelSemantics.toOffset_eval,
    ``PsKernelSemantics.addOffset_eval,
    ``PsKernelSemantics.explicit_eval,
    ``PsKernelSemantics.mkMax_eval,
    ``PsKernelSemantics.mkIMax_eval,
    ``PsKernelSemantics.instantiateParams_eval,
    ``PsKernelSemantics.AnnotatedExpr.erase_instLevels,
    ``PsKernelSemantics.SetModel.interp_instLevels,
    ``PsKernelSemantics.SetModel.satisfies_instLevels,
    ``PsKernelSemantics.SetModel.modelsType_instLevels,
    ``PsKernelSemantics.SetModel.instantiateLevelParams_has_reading,
    ``PsKernelSemantics.AnnotatedExpr.namesBelow_mono,
    ``PsKernelSemantics.AnnotatedExpr.namesBelow_liftN,
    ``PsKernelSemantics.AnnotatedExpr.namesBelow_inst,
    ``PsKernelSemantics.AnnotatedExpr.allocated_open_frame,
    ``PsKernelSemantics.inferCore_const_result,
    ``PsKernelSemantics.SetModel.const_inference_has_set_model,
    ``PsKernelSemantics.Declarative.fragmentReading,
    ``PsKernelSemantics.Declarative.relative_consistency
  ]
  let allowed : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]
  for target in targets do
    let used ← Lean.collectAxioms target
    for dependency in used do
      unless allowed.contains dependency do
        throwError "Unapproved axiom {dependency} in semantic declaration {target}"
  logInfo m!"PSKERNEL_SEMANTIC_AXIOMS: PASS declarations={targets.size}; local hypotheses remain explicit"
