import{k,tag,naturalValue,nil,randomGenerator}from'./binding-values.mjs';import{runtimeLevel}from'./fixture-values.mjs';export{k,tag,randomGenerator};
export const Z=['zero'],P=s=>['param',['str',['anonymous'],s]],S=x=>['succ',x],M=(a,b)=>['max',a,b],I=(a,b)=>['imax',a,b];
export function normalize(x,budget=20000){let state=k.psKernelUniverseStart(runtimeLevel(k,x));for(let i=0;i<budget;i++){const s=k.psKernelUniverseStep(state);if(tag(s)==='final')return{result:s.result,steps:i+1};state=s.state;}return{result:tag(state.tasks)==='nil'?k.psKernelUniverseFinish(state.values):k.PsKernelUniverseResult.outOfFuel,steps:budget};}
export function levelCheck(a,b,budget=20000){let state=k.psKernelLevelCheckStart(runtimeLevel(k,a),runtimeLevel(k,b));for(let i=0;i<budget;i++){const s=k.psKernelLevelCheckStep(state);if(tag(s)==='final')return tag(s.result);state=s.state;}return'outOfFuel';}
export function order(a,b,budget=20000){let tasks=k.PsKernelList.cons(k.PsKernelOrderTask.level(a,b),nil());for(let i=0;i<budget;i++){const s=k.psKernelOrderStep(tasks);if(tag(s)==='done')return tag(s.order);if(tag(s)==='invalidState')throw Error('invalid order');tasks=s.tasks;}throw Error('order budget');}
function text(x){const bytes=[];while(tag(x)!=='empty'){bytes.push(Number(naturalValue(x.value)));x=x.rest;}return new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(bytes));}
export function decodeName(x){switch(tag(x)){case'anonymous':return['anonymous'];case'str':return['str',decodeName(x.parent),text(x.value)];case'num':return['num',decodeName(x.parent),String(naturalValue(x.value))];default:throw Error('name');}}
export function decodeLevel(x){switch(tag(x)){case'zero':return Z;case'succ':return S(decodeLevel(x.value));case'max':case'imax':return[tag(x),decodeLevel(x.left),decodeLevel(x.right)];case'param':return['param',decodeName(x.name)];default:throw Error('level');}}
export function evaluate(x,a){switch(x[0]){case'zero':return 0;case'param':return a[JSON.stringify(x[1])]??0;case'succ':return evaluate(x[1],a)+1;case'max':return Math.max(evaluate(x[1],a),evaluate(x[2],a));case'imax':{const b=evaluate(x[2],a);return b===0?0:Math.max(evaluate(x[1],a),b);}default:throw Error('level fixture');}}
export function randomLevel(r,d){if(d===0)return r(3)===0?Z:P(r(2)?'u':'v');switch(r(5)){case 0:return Z;case 1:return P(r(2)?'u':'v');case 2:return S(randomLevel(r,d-1));case 3:return M(randomLevel(r,d-1),randomLevel(r,d-1));default:return I(randomLevel(r,d-1),randomLevel(r,d-1));}}
